### PR TITLE
Remove merchant Infield Loan Services

### PR DESCRIPTION
**Pull request by erciccione**
As requested on reddit by the owner

### CODE REVIEW

**Comment by luigi1111** [comment]
@erciccione would you mind linking to the post for reference?

**Comment by erciccione** [comment]
They wrote me a PM on reddit, so i asked them to write me from the email address listed (info (at)loandraw[dot]com ) to make sure i was talking with the legit owner. They did, so i opened this PR. I can provide a screenshot or forward the email if you want

**Comment by luigi1111** [comment]
Ah, I see. A screenshot of the email is fine.

**Comment by erciccione** [comment]
[Here it is](https://imgur.com/a/TqmUD) :)

**Pull request merged**
