### PR TITLE
roadmap - mark onion address goal as completed

### PR DESCRIPTION
**Pull request by sh5x5j12**

### CODE REVIEW

**Review by erciccione — CHANGES_REQUESTED** [review]
Thanks, but your commit message needs to be changed, right now it's a general `Add files via upload`.

**Comment by sh5x5j12** [comment]
> 
> 
> Thanks, but your commit message needs to be changed, right now it's a general `Add files via upload`.

I don't know how to change it. I guess i can't?

**Comment by erciccione** [comment]
I don't think it's possible with github's UI, but can be done locally with git. Let me know if you cannot do that, so that i can open the PR for you.

**Comment by sh5x5j12** [comment]
> I don't think it's possible with github's UI, but can be done locally with git. Let me know if you cannot do that, so that i can open the PR for you.

Yes, i cannot do that.

**Comment by erciccione** [comment]
Recovered in #1491.

The branch used to open this PR was deleted, so i had to recreate it. Closing this.

**Pull request closed without merging**
