### PR TITLE
Add Occidental Technologies to the list of Merchants

### PR DESCRIPTION
**Pull request by CM-IV**
Screenshot 2021-07-09 at 17-54-44 monero-project monero-site

I have added Occidental Technologies to the Merchant list, it was OK'd and the "needs investigation" status was removed.

### CODE REVIEW

**Comment by selsta** [comment]
IMO your website isn't too clear on what you exactly offer. It says "XMR accepted", but for what?

**Comment by CM-IV** [comment]
@selsta The description included in the application clearly states that Occidental Technologies is a web development/software engineering business.

My resume is also on the website showing that I am a computer scientist interested in that field.

**Comment by selsta** [comment]
Yes, I'm capable of reading the description. I was just giving you feedback, but if you think your current website is clear enough then whatever.

**Comment by CM-IV** [comment]
@selsta

I didn't mean anything negative...

What should I add to be more descriptive?  I have already included on the website that I am a Computer Scientist specializing in web development for hire.

A business owner could browse the directory with good ideas needing someone to implement them on the web.  Extra points if I can be paid for my work in monero.

**Comment by selsta** [comment]
I would add a separate "hire me" page (not a blog post) and be a bit more detailed on what you are offering, etc.

**Comment by CM-IV** [comment]
@selsta 

Ah I see..

I'll have those changes pushed up presently.

In the mean time, would adding the link to the merchant directory be appropriate?  Or would you like to see the results first?

**Comment by CM-IV** [comment]
@selsta 

Screenshot from 2021-07-09 23-06-47

Screenshot from 2021-07-09 23-07-55

**Review by erciccione — APPROVED** [review]

**Pull request merged**
