### PR TITLE
remove user guide 'how to run a node through i2p with i2p-zero'

### PR DESCRIPTION
**Pull request by erciccione**
i2p-zero has been dead for some time: https://github.com/i2p-zero/i2p-zero

### CODE REVIEW

**Review by hinto-janai — APPROVED** [review]

**Comment by hinto-janai** [comment]
Some feedback from: https://github.com/monero-project/meta/issues/824

Ideally, this would be replaced with a working guide for the currently recommended I2P (either i2p or i2pd, I'm not sure).

**Comment by creating2morrow** [comment]
> i2p-zero has been dead for some time: https://github.com/i2p-zero/i2p-zero

I don't think it is 'dead' per se. According to the readme.md:

    Note that I2P-zero is not a re-implementation of I2P. It uses the exact I2P source code from the official I2P GitHub repository.

It is actually quite useful for a project I'm working on with xmr and i2p for programmatically building and controlling tunnels. I had issues with http proxy but it was resolved by compiling new [binaries](https://github.com/creating2morrow/i2p-zero/releases/tag/v1.21-nevmes) with the `build-all-and-zip.sh` script.

**Comment by erciccione** [comment]
Any more feedback on this?

**Comment by creating2morrow** [comment]
> Any more feedback on this?

My vote is to just leave this for now since the guide still works and facilitates setting up remote nodes over i2p. There is a stagenet node at monero.fail setup, following the guide, for testing. The command for connecting is below. Once there is superseding documentation go ahead and remove the current guide.

```bash
./monero-x86_64-linux-gnu-v0.18.2.2/monero-wallet-cli --wallet-file stagenet/wallet/<WALLET_FILE> --proxy 127.0.0.1:9051 --daemon-address http://xmr3kaacphwkk4z2gp35bdl47lrrnzimmyqj4oliauqrjzqecofa.b32.i2p:38081 --stagenet --trusted-daemon --daemon-ssl-allow-any-cert
```

**Comment by nahuhh** [comment]
I would leave it alone for now. Plenty of guides online, not many correct, and i2p is broken in monero is configured incorrectly or reconfigured manually. 

i'll try to remember to update this after i2p anon inbound is fixed and i2pd etc can be used in place.

Also, iirc, bitcoin still recommends i2p-zero as well.

**Comment by plowsof** [comment]
> Some feedback from: [monero-project/meta#824](https://github.com/monero-project/meta/issues/824)
> 
> Ideally, this would be replaced with a working guide for the currently recommended I2P (either i2p or i2pd, I'm not sure).

+1 i left a comment [here](https://github.com/monero-project/monero-site/pull/1968#issuecomment-1783948345)..  moving from i2pzero -> i2pd is quite painless

**Pull request closed without merging**
