### PR TITLE
Add Stack Wallet to Downloads page

### PR DESCRIPTION
**Pull request by rehrar**
- Add PNG file
- Add another table row with Stack in Local Sync area

### CODE REVIEW

**Comment by rehrar** [comment]
Don't merge yet plz. A few bugs (in the wallet, not the PR) to iron out before "going live", but will notify when it's ready to go.

**Comment by erciccione** [comment]
There was no further communication so i'm assuming the wallet is still in testing. Feel free to reopen this PR when you think it's ready to be added to getmonero, so that the pr can be discussed and reviewed.

**Comment by plowsof** [comment]
any progress with those bugz / willingness to go live?

**Comment by rehrar** [comment]
Yes, we're ready to be added now @plowsof

**Comment by nahuhh** [comment]
> Yes, we're ready to be added now @plowsof 

Need to reopen the PR :P

**Comment by plowsof** [comment]
Czarek of XMRUW recently completed [milestone 1 of his ccs proposal](https://repo.getmonero.org/monero-project/ccs-proposals/-/merge_requests/437#note_25299). It's my understanding that StackWallet benefited directly/indirectly from this and is now running a new/updated wallet library which comes with (among other things) a lot of stability fixes.  Regular updates have been pushed out since this issue was made (over 1 year ago) and it seems stackwallet is here to stay ACK from me

**Review by plowsof — APPROVED** [review]

**Pull request merged**
