### PR TITLE
merchants: add secureshift.io

### PR DESCRIPTION
**Pull request by alphaRed03**
exchange add on of secureshift

### CODE REVIEW

**Comment by nahuhh** [comment]
Please change the title to:
`merchants: add secureshift.io`

**Comment by alphaRed03** [comment]
okay

**Comment by nahuhh** [comment]
Important questions (potential blockers):
1. How long has secureshift been swapping?
2. How long has secureshift had monero support?

bonus questions (not blockers):
i. Does secureshift have their own xmr reserves
ii. what is secureshift's aml policy (you can send a link)
iii. Does secureshift offer onion/i2p or have a no-logs policy?

thanks

**Comment by alphaRed03** [comment]
Hello, thank you for your questions.

1. SecureShift has been operating since March 2023.
2. SecureShift has supported XMR since the beginning of our operations, and a significant portion of our transactions involve XMR, which, along with some other cryptocurrencies, is a core value coin for us.

i. Yes, SecureShift maintains its own XMR reserves. There are no AML checks over XMR exchanges to any crypto. We do conduct AML checks on BTC, ETH, BNB, and some other coins and tokens.
ii. SecureShift's AML policy can be found here: [AML Policy](https://secureshift.io/terms-condition).
iii. We initially offered Onion/I2P services and had a no-logs policy. Currently, these services have been offline for the past year, but we plan to relaunch our online version soon.

**Comment by alphaRed03** [comment]
our exchange use misttrack aml

**Review by HardenedSteel — COMMENTED** [review]
https://secureshift.io/terms-condition
> 4.8 If you refuse to provide data about the origin of the funds sent or... ...SecureShift has the right to freeze the funds for the subsequent return of funds to the victims

What if there's no victim?

---

image
The website says SecureShift featured on getmonero.org, can you point us where we featured?

**Comment by alphaRed03** [comment]
In cases where we verify that there was no victim and the flag was false,
we will proceed to complete the exchange order as planned. However, if our
investigation finds that there was a legitimate concern, we will refund the
funds accordingly.

**Comment by HardenedSteel** [comment]
> In cases where we verify that there was no victim and the flag was false

> 4.8. If you refuse to provide data about the origin of the funds sent or provide false data, and if the data you provide confirms your connection to **criminal activity**, SecureShift has the right to freeze the funds for the subsequent **return of funds to the victims** with the assistance of law enforcement agencies.

What if the flag was true but there's no victim? Such as [victimless crimes](https://en.wikipedia.org/wiki/Victimless_crime). This should be clarified. 

and please answer the second question i asked above

**Comment by alphaRed03** [comment]
Regarding point 4.8, if the flag is accurate but there’s no identifiable
victim (e.g., in cases of victimless crimes), we should clarify that the
funds will be forfeited. Alternatively, the funds may be directed to a
donation, as per the administration’s decision.

**Comment by nahuhh** [comment]
What constitutes a crime?
What if its legal in my jurisdiction, but illegal in yours?

**Comment by alphaRed03** [comment]
What constitutes a crime may vary depending on the jurisdiction involved.
If an action is legal in your jurisdiction but illegal in ours, we will
assess the situation based on the laws and regulations that apply to
SecureShift, including international standards and compliance requirements,
such as those set by the Financial Action Task Force (FATF).

**Comment by HardenedSteel** [comment]
This information should be included in the terms and conditions

**Comment by alphaRed03** [comment]
Okay will included this points on terms and conditions

**Comment by alphaRed03** [comment]
Hello Team, any update regarding add on of secureshift

**Comment by HardenedSteel** [comment]
as I mentioned previously your website says its featured on getmonero.org while we didn't merge the pull request. why?

**Comment by alphaRed03** [comment]
Yes it was mentioned by hoping got listed😊

**Comment by HardenedSteel** [comment]
What about others? how Kraken and Binance featured Secureshift?

**Comment by alphaRed03** [comment]
Yes we they are liquid partner

**Comment by alphaRed03** [comment]
Sure we will change it with our new upcoming new design update

**Comment by alphaRed03** [comment]
Thank you for your feedback. Secureshift was launched in March 2023 after
years of development, and we’ve successfully completed over 10,000 orders
since then, which led us to apply for listing. Regarding our fees, we
charge a transparent 1% on all transactions, with no additional or hidden
charges.

We understand if the community feels we still need to earn the right to be
listed.

**Pull request closed without merging**
