### PR TITLE
Set anchors target for external urls to _blank

### PR DESCRIPTION
**Pull request by FedericoNembrini**
As discussed in #1921 and #1922, I set the target to `_blank` for links to external sites.

I have only modified links that comply with the css rule applied via `a[href^="https:"]:not([href*="getmonero.org"])` and which therefore display the `external.svg` icon

### CODE REVIEW

**Comment by plowsof** [comment]
If @erciccione could clarify the scope of this PR (`en` folders are mentioned [here](https://github.com/monero-project/monero-site/issues/1921#issuecomment-1365810169)) i can review/help if needed.

**Review by erciccione — APPROVED** [review]
looks good :)

**Comment by erciccione** [comment]
> If @erciccione could clarify the scope of this PR (en folders are mentioned https://github.com/monero-project/monero-site/issues/1921#issuecomment-1365810169) i can review/help if needed.

The en folders don't need  to be touched in this case as most if not all links are inside the documents themselves.

**Review by erciccione — APPROVED** [review]

**Comment by erciccione** [comment]
closes #1921

**Comment by erciccione** [comment]
@FedericoNembrini there are some conflicts that need to be solved before we can merge this.

**Review by erciccione — CHANGES_REQUESTED** [review]
Please fix the merge commit

**Comment by FedericoNembrini** [comment]
I have resolved the merge conflicts, have I forgotten something?

**Comment by erciccione** [comment]
@FedericoNembrini The last commit you pushed is a merge commit. That usually happens after a borked rebase. You could try to remove it and rebase again, fixing the merge conflict.

**Comment by FedericoNembrini** [comment]
I have resolved conflicts with github built in function.
I'll try to remove my last commit and do a rebase.

**Review by erciccione — APPROVED** [review]

**Comment by erciccione** [comment]
@FedericoNembrini please fix the conflicts and rebase :)

**Comment by erciccione** [comment]
ping @FedericoNembrini

**Comment by FedericoNembrini** [comment]
I will fix this in the coming days

**Comment by plowsof** [comment]
there is a plugin which claims to do this automagically for external links. i have not tested it yet but looks promising https://github.com/keithmifsud/jekyll-target-blank

**Pull request closed without merging**
