### PR TITLE
Add Monero Space meeting logs 2020-12-27

### PR DESCRIPTION
**Pull request by SamsungGalaxyPlayer**
Add Monero Space meeting logs 2020-12-27

### CODE REVIEW

**Review by erciccione — COMMENTED** [review]
This raises the question: What logs should we add to getmonero?

Personally, i'm not a fan of adding logs as blog posts. Blog posts are very slow to load and every new one make the website heavier. Is this a one time addition or you plan to add logs weekly/biweekly?

I would be fine with a one time addition, but if becomes a habit for workgroups to add logs as blog posts, we will soon find ourself with a clogged and slow website.

**Comment by erciccione** [comment]
Wait. Monero space has its own website. Why not post logs there?

**Comment by SamsungGalaxyPlayer** [comment]
Kovri and the MCW have their own websites, and logs still got added here. I think if you read the logs, they are highly relevant to Monero. We can consider adding to our own site as well, that's probably a good idea.

I think if you want to remove logs from the getmonero website, you should open a new issue suggesting that logs (dev diaries) should no longer be a blog post type.

**Comment by SamsungGalaxyPlayer** [comment]
Looks like there's some good reason to remove logs from the site entirely (I didn't know the build times were so long for text only), so closing.

**Pull request closed without merging**
