### PR TITLE
A new cheatsheet describing RCTTypeCLASG…

### PR DESCRIPTION
**Pull request by baro77**
…putting together concepts from previous infographics about Addresses and Rings flavours

### CODE REVIEW

**Comment by erciccione** [comment]
Thanks @baro77. Hopefully somebody from the MRL will review it soon :)

**Comment by baro77** [comment]
> Thanks @baro77. Hopefully somebody from the MRL will review it soon :)

my pleasure

**Comment by baro77** [comment]
Hope the CLSAG -> CLASG typo in PR title (just noticed :( ) isn't going to disqualify the content from being reviewed ;) lol

By the way, a screenshot just trying to rise interest :)
(Apart from jokes, thanks for your time, whenever it will be available)
RctCheatsheet20210604

**Review by UkoeHB — APPROVED** [review]
LGTM!

**Review by erciccione — APPROVED** [review]

**Comment by baro77** [comment]
thanks @erciccione , thanks @UkoeHB

**Pull request merged**
