### PR TITLE
update qubes/whonix isolation guide

### PR DESCRIPTION
**Pull request by 0xB44EFD8751077F97**
+ Add tips section for hardening.
+ Add table of contents.
+ Add usage examples.
+ Change steps and terminology for current Qubes (r4.0) and Whonix (14) versions.
+ Grammatical fixes and text edits.
+ Harden security:
  + Address access rights.
  + Clone new template for modifications.
  + Create system user for running the daemon.
  + Put the service file in `/lib/systemd/system/` on the TemplateVM, and enabled with the `qubes-service` condition path.
+ Opt for more thorough explanations, examples, and security over brevity.
+ Provide opportunity to extend for stagenet and testnet ports.
+ Remove unnessary arguments from service file.
+ Remove version numbers.
+ Rename guide, not exclusive to CLI anymore.
+ Rename `qrexec` action file and policy.
+ Replace section on verifying binaries with a link to Monero's user guide.

---

I hope I did everything the correct way. It was unclear from the readme on what to change the second and third version fields to. Readme says `1.0`, but I guessed that was a typo and should be `0`.

### CODE REVIEW

**Comment by 0xB44EFD8751077F97** [comment]
>you did not rename only the guide for English, but the file, making review quite complex. Please leave the file name untouch so we can review the changes (you could rename the file in another PR later).

I did rename the guide and the file, which is the proper way to do it. It didn't say anywhere in the readme to PR in steps when changing the name. Add it if you want, but this is what you get here. I don't care if review is complex, it should be, these are complex changes.

>The minor version was not a typo, it should be 1. However, was the old guides instruction really misleading? Are the steps so new that following the old guide was not possible?

Should it be `1`, because the readme says:

```
Changes that makes the old version false, or misleading to users: Increment the first number (Major version number) and reset the second and third to 1.0.
```

Which would make it `1.0`, not `1`. Yes, the old guide is now misleading, obsolete, and outdated. Do you even use Qubes? If not you can't review this anyway and you're wasting my time with these "complaints".

>Why do you clear out all translations with the english version? It is the purpose of guide versioning to help visitors consult a more accurate guide if the localized one is a bit (or much) outdated.

`5.6 Copy User Guide file into all languages` << that's why

**Comment by 0xB44EFD8751077F97** [comment]
@el00ruobuob You get paid to be here, I get paid to do stuff that I'm putting aside to answer your low level questions. The fact that you can't understand that is just more proof that you're wasting my time. When someone who knows what they're talking about gets here, I'll make whatever changes they want. As far as I'm concerned you are a waste of funds.

@rehrar please review

**Comment by el00ruobuob** [comment]
I will no try to argue more, as it seems it will be a loss of time for both of us.

**Comment by rehrar** [comment]
Lel. Now now kids.

I'll review tomorrow morning.

**Comment by rehrar** [comment]
Oh, I'm also super excited to try this on my Qubes 4.0! Thanks! :D

**Comment by qubenix** [comment]
Guide works for me. Really nice improvements/upgrades. I am especially excited about the AppArmor profiles.

One suggestion, in section `6.2` (using the GUI) put a link to the [GUI guide](https://github.com/monero-ecosystem/monero-GUI-guide/blob/master/monero-GUI-guide.md) like you did for the cli wallet section.

**Comment by 0xB44EFD8751077F97** [comment]
Added link to GUI guide, I didn't even know that existed. :+1:

**Comment by rehrar** [comment]
@0xB44EFD8751077F97 Everyone I'm very sorry. I've been traveling. Come back from Russia, have now traveled to Houston to give a presentation on Monero. I haven't forgotten this, and I'll be getting to it as soon as I can.

Several personal, professional, and Monero things have come up that need attending to. Thank you for your patience.

**Comment by 0xB44EFD8751077F97** [comment]
@rehrar Thank you for the update. I look forward to your review.

**Pull request closed without merging**
