### PR TITLE
New language localization (tr) underway - Updates so far

### PR DESCRIPTION
**Pull request by 7dNp8xK3Ed**
So far:
1. New language (Turkish) added into _config.yml file
2. New data folder created. Under lang, new tr folder created and all yml files translated (namely footer-1.yml, footer-2.yml, navigation.yml and roadmap.yml)
3. Under i18n, new folder "tr" created by cloning the template.
4. tr.yml fully translated.
5. "Turkish" as a new language been added into en.yml and es.yml files (so that the language also appears on other language versions of the site)
6. downloads.md, index.md, press-kit.md, techical-specs.md and the-monero-project.md translated.
7. Next: get-started folder.

### CODE REVIEW

**Comment by luigi1111** [comment]
@erciccione :) (I assume it's fine though)

**Comment by erciccione** [comment]
hehe lol, but yes, it's fine, just minor fixes

**Comment by 7dNp8xK3Ed** [comment]
Dear both,

Yes, this PR is ready to be merged (if you agree to it too, obviously).

I am working on the translation of the remaining and in-depth portion of the site, i.e. Moneropedia and Dev Guides. Those should possibly arrive in a separate PR.

Cheers!

**Comment by rehrar** [comment]
I don't think Moneropedia can be translated yet. It requires some custom Ruby scripting that I'm not able to do myself.

**Comment by 7dNp8xK3Ed** [comment]
Hi rehrar,

In that case the translation for Turkish can be marked as complete except for the dev guides. For those though, I will first need to have a good understanding of the guides before translating them in a meaningful manner which would make sense to the developers.

By the way, the Moneropedia files kind of look translatable to me? For example, account.md (and many others) are based in plain text just like the rest of the website docs. The only (minor) difficulty is to give consistent names for "@" which upon click, should direct you to a specific Moneropedia page. So far I managed it okay. (I already translated 6-7 files by the way).

By the way, should I mark this PR as closed or it should be done by the reviewers (or the person who'll do the merge)?

**Comment by rehrar** [comment]
@7dNp8xK3Ed can we get a rebase on this? :)

**Comment by 7dNp8xK3Ed** [comment]
@rehrar Resolved conflicts.

**Comment by erciccione** [comment]
@7dNp8xK3Ed the website doesn't build, you need to fix it creating 2 copies of the new guide `cli_wallet_daemon_isolation_qubes_whonix.md`. One need to go in `_i18n/it/resources/user-guides/` and the other one in `_i18n/tr/resources/user-guides`.

After doing that, please squash as suggested on reddit

**Comment by rehrar** [comment]
Blarg. Can we get one more rebase on this? Unfortunately the multi-language plugin constantly causes conflicts and I'm not really sure that can be resolved.

**Comment by erciccione** [comment]
@7dNp8xK3Ed Some commtis were pushed during these weeks. Can you rebase this PR please?

**Comment by erciccione** [comment]
Hey @7dNp8xK3Ed any news? are you still working on this?

**Pull request closed without merging**
