### PR TITLE
Roadmap update (Ledger support)

### PR DESCRIPTION
**Pull request by el00ruobuob**
This is a small update to the roadmap, to add ledger support as an achievement.

### CODE REVIEW

**Comment by el00ruobuob** [comment]
Tested ok on the following platforms:

  | Edge | IE 11 | Chrome | Firefox | Opera | Vivaldi
-- | -- | -- | -- | -- | -- | --
Windows 7 | - | OK | OK | OK | OK | OK
Windows 10 | OK | OK | OK | OK | OK | OK
Ubuntu 18.04 | - | - | OK | OK | OK | OK
CentOS 7 | - | - | - | OK | OK | OK

**Comment by el00ruobuob** [comment]
Ready for review @erciccione @mattcode55 @MaxXor

For already translated roadmaps, as usual @erciccione / @hrumag / @qwert95 & @zofiazinha, if you send me the localized sentence `Ledger Hardware Wallets Support`, i can add it to the PR.

**Comment by erciccione** [comment]
The Italian translation could be: `Supporto per hardware wallet Ledger`.

**Comment by el00ruobuob** [comment]
As they have the actual nano S and an upcoming Blue, I'll say Wallets...

**Comment by el00ruobuob** [comment]
thanks @erciccione it's added.

**Comment by zofiazinha** [comment]
Hi, here's the Polish translation:
Support dla portfeli Ledger Hardware.


Em qua, 13 de jun de 2018 10:44, erciccione <notifications@github.com>
escreveu:

**Comment by el00ruobuob** [comment]
Thanks @zofiazinha it's added.
Ready to merge is no more reviewer wants to say something.

**Pull request merged**
