### PR TITLE
Tools: add link to MoneroLogs

### PR DESCRIPTION
**Pull request by rating89us**

### CODE REVIEW

**Review by erciccione — CHANGES_REQUESTED** [review]
I think this will conflict with #1722, probably better to add this commit to that pull request instead of having a dedicated PR.

**Review by selsta — APPROVED** [review]

**Comment by selsta** [comment]
@erciccione conflict how? 1722 changes different files

**Comment by erciccione** [comment]
I linked to the wrong PR. I meant #1732, which changes the same file and almost the same line.

**Comment by selsta** [comment]
Should be fine to just rebase after 1732 is merged.

**Comment by erciccione** [comment]
Yeah, my point was to avoid the conflict and the need of rebase after the merge by putting the two commits in the same PR. Not a big deal, just makes maintainance easier.

**Review by erciccione — APPROVED** [review]

**Pull request merged**
