### PR TITLE
footer: fixed typo

### PR DESCRIPTION
**Pull request by salim-b**

### CODE REVIEW

**Review by erciccione — CHANGES_REQUESTED** [review]
Thank you, but your commit description is too generic. Something like `footer: fixed typo` would be better.

**Comment by salim-b** [comment]
@erciccione Ok, I've the changed the PR title accordingly.

**Comment by erciccione** [comment]
You changed the title of the PR, but not of the commit, which still says only `Fix typo`. If you are using github's interface, i'm afraid the easier way to fix this is to close this PR, redo the commit and then open another PR.

**Comment by salim-b** [comment]
@erciccione Happy now?

**Review by erciccione — APPROVED** [review]

**Pull request merged**
