### PR TITLE
Add merchants to list

### LINKED ISSUE #549: Add  Jeffscondos.com Vacation Rentals as Merchant
Can you please add Jeffscondos.com to your list of merchants under Travel & Lodging.
Please let us know what additional information is needed.

Thanks

Jeffscondos

### LINKED ISSUE #550: Add link to www.fierceedge.com as a merchant accepting Monero
Hi, I'm a merchant now accepting Monero! 

[Fierce Edge](https://fierceedge.com/) makes original design videogame inspired baselayers/rash guards/leggings and based in the UK.

### LINKED ISSUE #552: Add 2 sites as Monero merchant
Please add http://toys4sex.com.au - adult sex shop. And http://redcedarwebsites.com - digital marketing company

### PR DESCRIPTION
**Pull request by erciccione**
+ Closes #550 
+ Closes #549 
+ Closes #552 
+ Edits "MegaChange" merchant as requested in [#490 (comment)](https://github.com/monero-project/monero-site/pull/490#issuecomment-357238323)
+ Added toys4sex [as requested on reddit](https://www.reddit.com/r/Monero/comments/7psmme/our_company_based_in_australia_has_started_to/dsl32dx/?context=3) and midwestminers
+ Added Web4crypto as requested on reddit by PM

### CODE REVIEW

**Comment by MaxXor** [comment]
Maybe just squash all the commits into one.

**Comment by mattcode55** [comment]
^ Not sure, I think commits should be atomic.

**Comment by erciccione** [comment]
I prefer atomic commits in general, but i can squash if needed. @luigi1111 any preference?

**Comment by luigi1111** [comment]
@erciccione Atomic is fine. You seem to have a conflict presently. :)

**Comment by erciccione** [comment]
@luigi1111 Rebased

**Comment by luigi1111** [comment]
@erciccione Whoops.

**Comment by erciccione** [comment]
@luigi1111 re-rebased :P

**Comment by luigi1111** [comment]
@erciccione ecks dee

**Comment by erciccione** [comment]
@luigi1111 d'oh!
I thought atomic commits were also easier to revert. Anyway, rebased and squashed.

**Pull request merged**
