### PR TITLE
Minor French Update + NiceHash guide re-re-added

### PR DESCRIPTION
**Pull request by el00ruobuob**
This is a small update for fr.yml on which some sentences were missing translation since relocalization (why in hell didn't i see that before??)
This try (another time) to add the nicehash guide "How to mine Monero XMR without a mining equipement" which has always been here, but never been accessible through user-guide index page.

### CODE REVIEW

**Comment by el00ruobuob** [comment]
Tested OK on the following platforms:

  | Edge | IE 11 | Chrome | Firefox | Opera | Vivaldi
-- | -- | -- | -- | -- | -- | --
Windows 7 | - | OK | OK | OK | OK | OK
Windows 10 | OK | OK | OK | OK | OK | OK
Ubuntu 18.04 | - | - | OK | OK | OK | OK
CentOS 7 | - | - | - | OK | OK | OK

**Comment by el00ruobuob** [comment]
Added relocalization of Hangouts > StackExchange as disscussed with @erciccione in #764 
There is a new hoangout.stack_exchange_link variable in yml.
I took the French and Polish `Visit Stack Exchange` translations from the original PL and FR PR.
As ES PR does not include it, i'll have to rebase this part, and someone (@BlackLotus64?) will have to give me / put the ES version for this.
Will be tested soon.

**Comment by el00ruobuob** [comment]
Tested OK on the following platforms:

  | Edge | IE 11 | Chrome | Firefox | Opera | Vivaldi
-- | -- | -- | -- | -- | -- | --
Windows 7 | - | OK | OK | OK | OK | OK
Windows 10 | OK | OK | OK | OK | OK | OK
Ubuntu 18.04 | - | - | OK | OK | OK | OK
CentOS 7 | - | - | - | OK | OK | OK

**Comment by el00ruobuob** [comment]
I can rename if you want

**Comment by erciccione** [comment]
The problem is not in the name, it's that this PR include very different changes in one single commit (translations + re-adding a guide + a bug fix), that makes git history confusing and hard to review. Just a heads up for the next time

**Comment by el00ruobuob** [comment]
ok. noted then. I'll not try to limit the number of PRs if they aren't related.
Btw, it's not a massive rework if you want me to split them even for this one. Just ask.

**Comment by BlackLotus64** [comment]
Sure @el00ruobuob, when I get home I'll be ready to.

**Comment by el00ruobuob** [comment]
Rebased.

**Pull request merged**
