### PR TITLE
tools: fixed 4 broken links (removed 3)

### LINKED ISSUE #1980: Some websites not working in the resources/tools/ page
The ones not working:
- https://www.exploremonero.com/
- https://xmr.llcoins.net/ (certificate not valid)
- https://monerohash.com/nodes-distribution.html
- https://nownodes.io/connect-xmr-node (link to https://nownodes.io/nodes/monero-xmr instead?)
- https://www.backtestking.com/
- https://monerobase.com/
- https://vigla.biz/

### PR DESCRIPTION
**Pull request by erciccione**
Closes #1980

- changed link for nownodes
- removed backtestking
- removed monerobase
- removed vigla

### CODE REVIEW

**Comment by plowsof** [comment]
Is this from @HardenedSteel (there was an issue with rebasing / commit message)?

**Review by plowsof — APPROVED** [review]

**Comment by HardenedSteel** [comment]
> Is this from @HardenedSteel (there was an issue with rebasing / commit message)?

yes

**Comment by erciccione** [comment]
@HardenedSteel if you send me the email address you use for github, i can add you as co-author of the commit

**Comment by HardenedSteel** [comment]
> @HardenedSteel if you send me the email address you use for github, i can add you as co-author of the commit

@erciccione the e-mail address is visible in my profile.

**Comment by erciccione** [comment]
Added.

**Review by plowsof — APPROVED** [review]

**Pull request merged**
