### PR TITLE
Add merchant - monerujo Monero Wallet for Android

### PR DESCRIPTION
**Pull request by hampusohlsson**

### CODE REVIEW

**Comment by MaxXor** [comment]
What about linking to https://monerujo.io/ instead of the playstore url?

**Comment by hampusohlsson** [comment]
Good point, I'll update

**Comment by MaxXor** [comment]
Nice, could you squash the two commits into one? Then it's ready to get merged I think.

**Comment by hampusohlsson** [comment]
Fixed

**Comment by SamsungGalaxyPlayer** [comment]
Can't it be added here too? https://getmonero.org/downloads/#mobilelight

**Comment by hampusohlsson** [comment]
Added it to download section too

**Comment by rehrar** [comment]
Thank you for your work, but that reddit thread and this PR could not have come at a worse time. Take the $40 of XMR, I don't want it, but this PR should not be merged due to #527 which adds Monerujo, but in the new format. :)

**Comment by hampusohlsson** [comment]
Haha no worries! It's just awesome that the community is moving forward

**Comment by luigi1111** [comment]
Added in #527

**Pull request closed without merging**
