### PR TITLE
devguides: add proxy to wallet-rpc set_daemon

### PR DESCRIPTION
**Pull request by plowsof**

### CODE REVIEW

**Comment by 0xFFFC0000** [comment]
Thanks @plowsof 
If we add `Syntax: <HOST:PORT>` to the end of the doc, it would be much better IMHO.

**Comment by plowsof** [comment]
I was about to ask you for that, will add. Thanks!

**Comment by plowsof** [comment]
@0xFFFC0000 added syntax

**Comment by nahuhh** [comment]
Note: Need followup pr to change L145.
The default, if blank, is `127.0.0.1:18081

https://github.com/monero-project/monero/pull/9211#issuecomment-1972070341

**Comment by plowsof** [comment]
docs are moving to https://github.com/monero-project/monero-docs

merged in https://github.com/monero-project/monero-docs/pull/67

closing. thank you

**Pull request closed without merging**
