### PR TITLE
home: align moneropedia card

### PR DESCRIPTION
**Pull request by alreadyburnt**
Fix card alignment.

### CODE REVIEW

**Review by wirrickelliot — COMMENTED** [review]
Looks good although I would suggest starting your commit message with "home:" since there are multiple index.html files. And then change the PR title to match.

**Comment by wirrickelliot** [comment]
Please update the commit message as well.

**Comment by alreadyburnt** [comment]
These are my first days with git so I don't really know how it works. There seem to be no such option from the web interface so I'm trying now from the cli. I hope not to mess up haha.

**Review by wirrickelliot — APPROVED** [review]
Thanks :)

**Review by erciccione — APPROVED** [review]

**Pull request merged**
