### PR TITLE
Prepare repo for deployment of onion service 

### LINKED ISSUE #904: Create a .onion mirror of the site
*Issue originally created by @Electricsheep01*

*This issue was created on gitlab and then migrated here. Only the original post was migrated, not the comments. Please take a look at the discussions on the original Gitlab issue before commenting here: https://repo.getmonero.org/monero-project/monero-site/-/issues/958*

---
It is quite probable that the FATF is going to start cracking down on privacy focused projects like Monero soon. We should really have .onion mirror(s) of getmonero.org for those who need that extra layer of protection.

### PR DESCRIPTION
**Pull request by erciccione**
Requires #1452
Closes #904

~~`onion.txt` is just a draft, needs to be improved and signed.~~

### CODE REVIEW

**Comment by binaryFate** [comment]
I suggest to sign this:
```
# You can check the signature against binaryFate key available in
# Monero source code at utils/gpg_keys/binaryfate.asc.
#
# Main site (www.getmonero.org):
http://monerotoruzizulg5ttgat2emf4d6fbmiea25detrmmy7erypseyteyd.onion

# Download subdomain (downloads.getmonero.org):
http://dlmonerotqz47bjuthtko2k7ik2ths4w2rmboddyxw4tz4adebsmijid.onion
```

* I don't think we should tie us down to github in particular, so I removed that reference from your draft.

* I removed the mention to _includes/onion.html; I think it would mostly confuse people. (However, the other way around, mentioning in onion.html that people should ideally check onion.txt is a good idea)

**Comment by erciccione** [comment]
@binaryFate I agree with the changes.

> mentioning in onion.html that people should ideally check onion.txt is a good idea

That was my first thought, but it's not possible or the comment will be pulled along with the address, messing the format. i'm fine with having no mention tho, we can point to the onion.txt file somewhere else on the website (beside the README, where i already mention it) if we want to.

**Comment by binaryFate** [comment]
Suggestion 2, with a bit more info:
```
# This file contains the onion addresses used by getmonero.org and
# downloads.getmonero.org
#
# You can check the signature against binaryFate key available in
# Monero source code at utils/gpg_keys/binaryfate.asc.
#
# Main site (getmonero.org):
http://monerotoruzizulg5ttgat2emf4d6fbmiea25detrmmy7erypseyteyd.onion
# 
# Download subdomain (downloads.getmonero.org):
http://dlmonerotqz47bjuthtko2k7ik2ths4w2rmboddyxw4tz4adebsmijid.onion
```

**Comment by erciccione** [comment]
> Suggestion 2

Ok for me.

**Comment by binaryFate** [comment]
Here it is, you can add it directly:

```
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA256

# This file contains the onion addresses used by getmonero.org and
# downloads.getmonero.org
#
# You can check the signature against binaryFate key available in
# Monero source code at utils/gpg_keys/binaryfate.asc.
#
# Main site (getmonero.org):
http://monerotoruzizulg5ttgat2emf4d6fbmiea25detrmmy7erypseyteyd.onion
# 
# Download subdomain (downloads.getmonero.org):
http://dlmonerotqz47bjuthtko2k7ik2ths4w2rmboddyxw4tz4adebsmijid.onion
-----BEGIN PGP SIGNATURE-----

iQIzBAEBCAAdFiEEgaxZH+nEtlxYBq/D8K9NRioL35IFAmAjBeIACgkQ8K9NRioL
35JaTg/9GWJ7ogJD64TgtAKDV5vPH+mPVMQt47J0znMBhR3z++cNIaESh0mkpAje
2YTRdTUjFUaZq8emosV+xdzo6KamfeA0hapVeI1zQ6eBNzjYIjN/jOD2/hcFi/6n
3ywG7nmFlnnnSs8ef/MNXq0HiE8OsyQZfD1UBsIazIJTXr8aKvvsJG8IPmHggTr9
mY7LIQdtA7wZqdaSpnN4Ah9HrRF3/b2b6Hwnz1ACbi8X4mdAQ07Y87GhowUWMwoV
Ki0k+T500kA09AuS7RD0YDJxi3N4i7hU2d8vJCUlgGQMrdHZMZiy3DLVvZAdyOzR
QnE4Y0Q3cBUcRRPIrAXNBbYWtUUNh1ujza4WanZ0FQrC9yDoldnTvQMUllOesakb
7HyfY/ujPlbUfwP/SEQVizqnk/5IHSdSB1vDtxXf1kYJx2Dp05Fz/D32vGSXXLQi
TSaVfHS0KYHzWOq362SJqhssZQ0MStbTxdKnzAYx1lBrrHE27Y64ek+uv4tNpDNe
s/XqMS1+2wPc4ZSsyXAlcxbs/V6hJtGDOxr2UNiqOrjteSxJmxrkBHq9L/qrlUJo
k/5nerhUtDUkHIMYaOpBJUbq+9RfiTlU8IU6mnVwPzSGxRgygcLxT1TmdAlhoZ/x
a6a/heb6qLUNkBYZTLo9Hd9U2l6TyQ+WjD1UTafE7RkqU55zJ7g=
=cZhI
-----END PGP SIGNATURE-----
```

**Comment by erciccione** [comment]
Added and signature checked.

**Comment by erciccione** [comment]
Added the onion-location header (https://community.torproject.org/onion-services/advanced/onion-location/)

**Review by binaryFate — APPROVED** [review]

**Comment by ChanarinThintip** [comment]
Good

**Pull request merged**
