### PR TITLE
New sponsor

### PR DESCRIPTION
**Pull request by MajesticBank**
Adding new sponsor on site

### CODE REVIEW

**Comment by binaryFate** [comment]
I can confirm MajesticBank has paid today for the next quarter (May/June/July) of website hosting, total $6k.

**Comment by binaryFate** [comment]
Btw should not say "the CDN used by this website" (That is paid by Tari labs), but "the server used by this website".

**Review by erciccione — CHANGES_REQUESTED** [review]
The only file that should have string changes is `_i18n/en.yml`. Weblate will automatically provide translatable strings to translators, adding translations directly to the code could cause conflcts. Please edit :)

**Comment by MajesticBank** [comment]
Cheers guys, should be better now

**Review by erciccione — CHANGES_REQUESTED** [review]
Please squash your commits into 1.

**Comment by plowsof** [comment]
please close, merged in #1994

**Pull request closed without merging**
