### PR TITLE
devguides: add set_bootstrap_daemon to daemon rpc

### PR DESCRIPTION
**Pull request by plowsof**

### CODE REVIEW

**Review by selsta — APPROVED** [review]

**Comment by erciccione** [comment]
Thanks for taking care of this @plowsof, very needed. Soon i'll be able to dedicate some time to reviewing PRs, but in the meantime i noticed there is a stream of PRs changing the same file:

- https://github.com/monero-project/monero-site/pull/2058
- https://github.com/monero-project/monero-site/pull/2061
- https://github.com/monero-project/monero-site/pull/2064
- https://github.com/monero-project/monero-site/pull/2077
- https://github.com/monero-project/monero-site/pull/2077
- https://github.com/monero-project/monero-site/pull/2059
- https://github.com/monero-project/monero-site/pull/2060
- https://github.com/monero-project/monero-site/pull/2066
- https://github.com/monero-project/monero-site/pull/2066
- https://github.com/monero-project/monero-site/pull/2069
- https://github.com/monero-project/monero-site/pull/2070
- https://github.com/monero-project/monero-site/pull/2068
- https://github.com/monero-project/monero-site/pull/2065
- https://github.com/monero-project/monero-site/pull/2056

Merging these PRs would result in 15 commits for the same file, it's a significant bloat for git can can be easily avoid. Would be better instead to have one single commit and a single WIP PR.

**Comment by selsta** [comment]
@erciccione we already planned to merge them to a single PR

**Comment by erciccione** [comment]
@selsta even if git bloat doesn't exist (and my understanding is that it does, unless something has changed in the last years. I struggle to think that's the case though, even only because each pr also creates a merge commit. So this would have been 15 commits + 15 merge commits. Definitely unnecessary and real bloat), opening multiple PR for the same file is something we have never did before in this repository (but i remember luigi asking to group PRs in other repositories too), so i don't see the reason to deviate from this approach.

For reference, every time there was to update the dev guide i always opened a single draft PR where i kept track of the calls that needed to be added and when i had all of them or most of them, i opened a single pr. IIRC this was specifically requested from luigi, but i might be remembering wrong. In any case that's what we have been doing until now.

**Comment by plowsof** [comment]
This has been a learning experience for me, i used the multiple PR's as a way to get them individually reviewed / approved. Later on i cherry-picked each and handled the annoying conflicts one-by-one (to save luigi doing this)

Some days ago, I asked selsta to review some of the PR's that where ready and he made a passing comment that there will be merge issues with all these PR's editing the same 2 files (i was unaware of the extent to which this would be a problem) - i then began taking the approved PR's and placing them into a single PR / closing my others. 

This all happened within the last 24 hours and it is my fault for not discussing my plans / intentions publicly, so i apologise for any confusions caused. Moving forward i will make sure to discuss my plans publicly, and keep changes to the same file(s) inside 1 PR.

The new PR with multiple commits has been merged for luigi so there are no conflicts and indeed , it retains credit where credit is due (when i have taken other peoples answers). I have not heard his opinion on that PR yet.

**Pull request closed without merging**
