### PR TITLE
faq: add period to description

### PR DESCRIPTION
**Pull request by alreadyburnt**

### CODE REVIEW

**Review by erciccione — APPROVED** [review]
I guess it's fine for consistency, since we put a dot in the other descriptions.

**Comment by luigi1111** [comment]
Disagree. If you (=anyone) want to make it a sentence, go ahead. The other intros I looked at were at least sentences, and even if they weren't, I'd rather remove the errant period than add it here.

**Comment by alreadyburnt** [comment]
I'm not sure such a change is required just to add the period. However if u think so here's my proposal.

**Review by luigi1111 — APPROVED** [review]
Thanks.

**Pull request merged**
