### PR TITLE
Library page & content

### PR DESCRIPTION
**Pull request by el00ruobuob**
This is a new Library page, link from ressources and footer.
Accessed through `https://getmonero.org/library/`
Books and other ressources accessibles from `https://getmonero.org/library/<filename>`

It includes a new section in yaml localized (_i18n) file, with list of publications categories (books, magazines), each categories including list of publications. @erciccione, please give your thoughts if any.

Actual Books & magazines published are:
- Books
  - Preview of Mastering Monero (all credit goes to @serhack)
  - Zero to Monero (all credit goes to @UkoeHB)
- Magazines
  - Revuo Monero Q3 2017 (all credit goes to @rehrar)
  - Revuo Monero Q4 2017 (all credit goes to @rehrar)

This replace & enhance #769, discussed in #771, with agreement of @UkoeHB.

Tested OK on the following platforms:

  | Edge | IE 11 | Chrome | Firefox | Opera | Vivaldi
-- | -- | -- | -- | -- | -- | --
Windows 7 | - | OK | OK | OK | OK | OK
Windows 10 | OK | OK | OK | OK | OK | OK
Ubuntu 18.04 | - | - | OK | OK | OK | OK
CentOS 7 | - | - | - | OK | OK | OK

### CODE REVIEW

**Comment by el00ruobuob** [comment]
Thanks @SamsungGalaxyPlayer. I just updated the Readme accordingly, it may need a new review.

**Comment by UkoeHB** [comment]
Yay thank you :)

**Comment by serhack** [comment]
Yea, thank you!

**Comment by UkoeHB** [comment]
Hey I updated the document with:
-MLSAG key prefixing footnote (pg 25)
-formatting (pg 65)

Would you mind updating PR with new PDF from [here](https://github.com/UkoeHB/Monero-RCT-report)?

**Comment by el00ruobuob** [comment]
Sure, i just did @UkoeHB

**Pull request merged**
