### PR TITLE
fix: typo from wich to which

### PR DESCRIPTION
**Pull request by clarkkozak**
https://wikidiff.com/wich/which

### CODE REVIEW

**Review by erciccione — APPROVED** [review]

**Comment by erciccione** [comment]
@clarkkozak this needs to be rebased.

**Comment by clarkkozak** [comment]
@erciccione I gave it my best shot :grimacing: I'm unsure if I did it right though. Do you have any resources on the best way to do it in this repo? Would you rather me open up a new PR? Let me know how I can help :)

**Comment by clarkkozak** [comment]
next time i'll force update the branch :)

**Comment by erciccione** [comment]
@clarkkozak yeah the PR got borked, as you can see from all those commits :). The easiest way to fix it's probably to open a new PR, let me know if you need help with that.

**Comment by clarkkozak** [comment]
@erciccione closing this one. reopened in #1344

**Pull request closed without merging**
