### PR TITLE
Add more new merchants.

### PR DESCRIPTION
**Pull request by el00ruobuob**
Closes:
- #726 Crypto Clothing 
- #727 Urban Detail

### CODE REVIEW

**Comment by el00ruobuob** [comment]
ping aprovers @erciccione @mattcode55 @MaxXor

**Comment by rehrar** [comment]
Only approve.

**Comment by luigi1111** [comment]
@el00ruobuob please rebase.

**Comment by el00ruobuob** [comment]
was rebased...

**Pull request merged**
