### PR TITLE
Add StealthEX to the Swappers section

### PR DESCRIPTION
**Pull request by DarkVan300**

### CODE REVIEW

**Comment by selsta** [comment]
Hello, please see the comments here: https://github.com/monero-project/monero-site/pull/1913

We currently don't add any websites unless they 1) exist for a while and 2) have a good reputation in the community. I think StealthEX isn't well known enough in the community to add it yet.

**Comment by plowsof** [comment]
Noted. also i seen one of your representatives take part in a Monerotopia [interview](https://yewtu.be/watch?v=5Ekf5sqwrL8) recently

**Comment by DarkVan300** [comment]
Hi there, we have read the recap of the meeting and understand that we need more feedback from the Monero community. If you could let us know the preferred method and threshold for the community feedback that would be great!
If it brings any relevance, we already work with several renowned members of the community, OrangeFren and Justin Ehrenhofer (Cake Wallet). Happy to put in the additional effort too.
Thanks!

**Review by erciccione — COMMENTED** [review]
This PR has been open for a long time, i'd say at this point we either add stealthex.io or reject them.

Please post feedbacks. If there is no or negative feedback i'd just close the PR.

**Comment by DarkVan300** [comment]
Thank you for pushing the process forward!
We have been working on our service and general standing in the community. We are affiliated with services that are known within the Monero community, Trocador, Orangefren, Moneroj are few to name! We have been consistently supporting Monerotalks for almost a year and always there to put an additional effort for the community. Happy to answer any questions and would be honored to be added!

**Comment by cryptomorpheuss** [comment]
From being in touch with StealthEx on a regular basis because of Moneroj.net and other services, I can say that they are very reliable and they support privacy as a tool for freedom as well. No users from our services have ever been let down, so I strongly support this.

**Comment by DarkVan300** [comment]
Hi everyone,

Cryptomorpheuss thank you for your feedback. We have noticed that the PR still hangs in the open. We believe that we will be a valuable addition to the directory and provide utility for the community. Let us know if there is anything that may be required on our side. Thanks!

**Review by nahuhh — APPROVED** [review]

**Pull request closed without merging**
