### PR TITLE
Add bottom margin for 404 page

### PR DESCRIPTION
**Pull request by HardenedSteel**
Before:
image
After:
image

### CODE REVIEW

**Comment by HardenedSteel** [comment]
I broke somethings for deployment.

**Review by erciccione — CHANGES_REQUESTED** [review]
Please do not use inline styling, but edit the `css/custom.css` file instead.

**Comment by HardenedSteel** [comment]
Since all buttons have same class names i don't know how to change specific class without inline styling

**Review by erciccione — CHANGES_REQUESTED** [review]
This is not an acceptable solution, as it would break other pages.

Could you share what browser are you using so we can test things out?

**Comment by HardenedSteel** [comment]
@erciccione Firefox.

**Comment by erciccione** [comment]
This PR cannot be accepted. I opened an issue to track the problem: #1920

**Pull request closed without merging**
