### PR TITLE
Add 3xpl.com Block Explorer

### PR DESCRIPTION
**Pull request by coincashew**
Fastest block explorer added XMR support in 2023. Onion site available too.

### CODE REVIEW

**Comment by nahuhh** [comment]
Idk about "fastest", but i discovered this site recently and it has some good data tools as well.

at first impression, i like it.
@rucknium

**Comment by nahuhh** [comment]
https://3xpl.com/monero

**Comment by plowsof** [comment]
the void / shielded pool? https://3xpl.com/monero/mempool
get receipt downloads a pdf? https://3xpl.com/monero/transaction/3b591281757ab44e133f9b40eec2fc5fbfb26175038e08cd208f7eabbc2581b3
is their discord link to gain access invaid? https://discord.com/invite/twCa6g2Bge

**Comment by plowsof** [comment]
NACK , please close/reopen when it works, see above

**Comment by plowsof** [comment]
please re-open when the above issues have been addressed, closing

**Pull request closed without merging**
