### PR TITLE
Revert "downloads: hide remote sync section until wallets upgrade to v16

### PR DESCRIPTION
**Pull request by erciccione**
This reverts commit 22f72b05de8d78d2c9c2a614769da25033e246d8.

To be merged after Mymonero and edge will be confirmed on the correct network.

Edge: https://twitter.com/EdgeWallet/status/1563584457361149952
i'm unsure about the current status of Mymonero. Ping @LivBoss @AslanPonies

### CODE REVIEW

**Comment by LivBoss** [comment]
> This reverts commit [22f72b0](https://github.com/monero-project/monero-site/commit/22f72b05de8d78d2c9c2a614769da25033e246d8).
> 
> To be merged after Mymonero and edge will be confirmed on the correct network.
> 
> Edge: https://twitter.com/EdgeWallet/status/1563584457361149952 i'm unsure about the current status of Mymonero. Ping @LivBoss @AslanPonies

And we are very happy to report that our Android app has been successfully patched and is operational again.

This now means that you can now view your XMR balance and transactions again, since the wallets are scanning to the latest block height within our Web-Wallet, MacOS, Linux and Android mobile app.

Our engineers are busy with the spend patch, which directly relates to sending funds. This is expected to be completed early this upcoming week.

We are also in the final stages of patching the Windows system. We are ready to release the iOS mobile app, we are just working through a few things with the Apple review team.

**Comment by LivBoss** [comment]
@erciccione 
Here is the latest official from the MyMonero team:

MyMonero has hard forked, Our software is now compatible with the Fluorine Fermi network upgrade.

Our wallet is fully operational on our web-wallet, MacOS, Linux platforms, as well as on theAndroid and iOS mobile apps.

Once you have updated to the latest software, you will be able to see your balances and transactions and you can now send XMR.

With regards to our Windows users, we have completed the hard fork patch on the Windows software as well, and although we are very eager to release it, we are still awaiting a certificate that will allow us to release the software publicly.

**Comment by LivBoss** [comment]
Official PSA from MyMonero:

We have just released our upgraded software for Windows.

Our Windows users can now download the latest software here: 
https://github.com/mymonero/mymonero-app-js/releases/download/v1.3.2/MyMonero-Setup-1.3.2.exe

We are happy to announce that MyMonero is now fully operational on 100% of our platforms.

**Comment by selsta** [comment]
I can confirm that sending worked for me with the MyMonero version on iOS.

**Review by selsta — APPROVED** [review]

**Pull request merged**
