### PR TITLE
sponsors: remove globee

### PR DESCRIPTION
**Pull request by erciccione**
Globee, for their own reasons, unrelated to Monero, is no longer sponsoring Monero's infrastructure.

### CODE REVIEW

**Comment by fluffypony** [comment]
FWIW it's not a lack of desire from GloBee's part, it's purely financial reasons. I'm sure we're grateful for the years they sponsored the server. If anyone is interested in taking over sponsorship let us know, else it'll continue to be covered by the general fund.

**Comment by erciccione** [comment]
Maybe would make sense to have a "past sponsors" section? To give credits to entities that sponsored in the past? [Tor has one](https://www.torproject.org/about/sponsors/) for example.

**Comment by fluffypony** [comment]
Not a bad idea! Also note that Tari Labs continues to cover the CDN, that hasn't changed. cc @carrington1859

**Comment by carrington1859** [comment]
> Not a bad idea! Also note that Tari Labs continues to cover the CDN, that hasn't changed. cc @carrington1859

TY for the clarification. Updated.

**Comment by escapethe3RA** [comment]
> If anyone is interested in taking over sponsorship let us know, else it'll continue to be covered by the general fund.

Posted as a community message on MO for more exposure: https://www.monero.observer/fluffypony/

Let me know if that's okay and if you want me to add more details.

@fluffypony

**Review by SamsungGalaxyPlayer — APPROVED** [review]

**Pull request merged**
