### PR TITLE
Update confidential_para1 to "a" not "the only" cryptocurrency

### PR DESCRIPTION
**Pull request by citrus-flagman**
Changed "Monero is the only cryptocurrency where every user is anonymous by default." to "Monero is a cryptocurrency where every user is anonymous by default." to address issue [1934](https://github.com/monero-project/monero-site/issues/1934)

### CODE REVIEW

**Review by erciccione — CHANGES_REQUESTED** [review]
As said in the issue, i think would be better to use `"The only major cryptocurrency" instead. A cryptocurrency is just... weak.

Please do not change the string in other languages. That needs to be done on weblate to avoid conflicts.

**Comment by citrus-flagman** [comment]
@erciccione I have removed the incorrectly added translations and changed "a cryptocurrency" to "the only major cryptocurrency".

**Review by erciccione — CHANGES_REQUESTED** [review]
The checks seem to be failing for some reason. Please squash the commit to only 1

**Comment by citrus-flagman** [comment]
@erciccione I have squashed the commits to only 1 and it looks like the checks are passing now.

**Review by selsta — APPROVED** [review]

**Review by erciccione — APPROVED** [review]

**Pull request merged**
