### PR TITLE
New release CLI&GUI, v0.18.3.2

### PR DESCRIPTION
**Pull request by binaryFate**
New hashes for release CLI&GUI, v0.18.3.2
Add new hash for linuxriscv64
Rename links risc -> riscv

### CODE REVIEW

**Comment by plowsof** [comment]
`Good signature from "binaryFate <binaryfate@getmonero.org>"` on hashes.txt, needs squashing?

**Comment by binaryFate** [comment]
In progress. Please wait for workflows to validate properly before reviewing.

**Comment by plowsof** [comment]
looking at the filename script

**Comment by binaryFate** [comment]
Ok, ready to merge. Please check the hashes.

**Review by selsta — APPROVED** [review]
Hashes verified and RISC-V correctly added.

**Review by plowsof — APPROVED** [review]

**Pull request merged**
