### PR TITLE
Typo on developer guide > daemon RPC line 257, 662 & 780:

### PR DESCRIPTION
**Pull request by el00ruobuob**
"notice that the returned information is the save as in the previous example"

"s/save/same/"

### CODE REVIEW

**Comment by el00ruobuob** [comment]
Another small typo with "ignatures" instead of "signatures", twice per files.

**Comment by el00ruobuob** [comment]
I just finished my translation and did not found more typos in the file.

**Comment by el00ruobuob** [comment]
Sorry @erciccione & @MaxXor i pushed another pair of correction after your approvals... Could you re-approve?

**Comment by MaxXor** [comment]
Looks good, please squash the two commits into one.

**Comment by el00ruobuob** [comment]
squashed it is!

**Pull request merged**
