### PR TITLE
README: fix introduction text

### PR DESCRIPTION
**Pull request by rating89us**
- Add a table of contents, like monero and monero-gui repositories use. 
- Remove "Introduction" title
- Some fixes to the introduction text

### CODE REVIEW

**Review by erciccione — CHANGES_REQUESTED** [review]
We removed the TOC not long ago (#1595) because it's provided by Github, so we don't need to maintain it. I don't see any benefit in adding it again.

I think substituting "README" with "guide" is not correct (maybe "document" would fit better), but in any case this a very minor and arbitrary change. I don't think worth having a dedicated commit for it. We should really limit changes related to personal preferences.

**Comment by rating89us** [comment]
1) There is clearly an error in this sentence:
image

2) TOC was reintroduced in monero-gui README since TOC button is really hidden on github interface. Many users don't even know this button exists:
image
image

**Comment by selsta** [comment]
> Not everyone knows what a "README" is. So I think it's better to use a more familiar term like "guide", "document", or "page".

Keeping it README should be fine, everyone capable of contributing to the monero-site repository will know what it is. Otherwise they won't read it anyway.

**Comment by erciccione** [comment]
> There is clearly an error in this sentence:

Sure, let's fix it, but that's unrelated to change the word README to something else.

> TOC was reintroduced in monero-gui README

@rating89us I still think it's not necessary to add a TOC when the platform we use autogenerate one and it's just one click away. The fact that you preferred to re-add the TOC to the GUI and people had no problems with it it's not a good reason to add it again everywhere, especially when we removed it from this repo not long ago.

**Comment by selsta** [comment]
Please squash.

**Review by selsta — APPROVED** [review]

**Review by erciccione — APPROVED** [review]

**Pull request merged**
