### PR TITLE
Removing broken link to Rocket Chat rocket.xmrnation.com

### PR DESCRIPTION
**Pull request by jonathancross**

### CODE REVIEW

**Comment by jonathancross** [comment]
Hi @fluffypony, any concerns here?

Seems the website is no longer 404, but instead points to an Indonesian Motorcycle dealer :-/

**Comment by fluffypony** [comment]
Sorry will merge website PRs tomorrow

**Comment by jonathancross** [comment]
Cool, thanks.

**Comment by jonathancross** [comment]
Friendly ping @fluffypony

**Pull request merged**
