### PR TITLE
css/custom.css: correct hangouts icon coordinates

### PR DESCRIPTION
**Pull request by plowsof**
replaces / includes #2307 *Add discord to hangouts

opening the spritesheet in GIMP to obtain pixel correct values:

- Pre coordinaudit 

| Icon  | Default XY | Hover XY | Size | pxl spacing below | between |
| --- | --- | --- | --- | --- | --- |
| Facebook | 128 0 | 176 0 | 43x43 | 5 | 5 |
| Twitter  | 128 48  | 176 48 | 43x43 | 5 | 5 |
| Reddit | 128 96 | 176 96 | 43x43 | 5 | 5 |
| Github | 128 144 | 176 144 | 43x43 | 5 | 5 |
| Gitlab | 128 190 | 176 190 | 43x43 | 3 | 5 |
| Telegram | 127 236 | 176 236 | 45x45 | x | 4 | 

all issues fixed in this PR:
- center gitub icon
- telegram / discord icon resize to 43x43
- consistent spacing between icons (5 pixels below/between)

so we now have 43+5 actual spacing to avoid confusing the next generation

### CODE REVIEW

**Comment by plowsof** [comment]
the discord link here does not work for me, i see invitation invalid  https://discord.gg/SyGUMWBqvF

**Comment by nahuhh** [comment]
https://discord.com/invite/SyGUMWBqvF

does this one work?

**Review by nahuhh — APPROVED** [review]

**Comment by HardenedSteel** [comment]
can we just split the icons? which would be easier to work in future

**Comment by nahuhh** [comment]
> can we just split the icons? which would be easier to work in future

We were already using a (broken) sprite sheet. This PR has 2 commits. 
1. fixes the broken sheet
2. pulls in discord commit

IMO, if we want to change the sprite to individual icons, that is a new PR

**Comment by plowsof** [comment]
sprites have pros/cons. reducing network requests to getmonero by allowing clients to used the cached image seems beneficial enough to just fix/set and forget as we don't work with them often/ever. a PR adding new separate icons would only be warranted if it came with a redesign or quality increase without any increase in network load to the server using fancy new tech (im not qualified enough to produce such a PR of course)

**Comment by nahuhh** [comment]
also:
```
- Maintainers SHALL merge correct patches from other Contributors rapidly.
- Any Contributor who has value judgments on a correct patch SHOULD express these via their own patches.
```

**Review by HardenedSteel — APPROVED** [review]

**Pull request merged**
