### PR TITLE
MRL: add note to arcturus paper (was retracted)

### PR DESCRIPTION
**Pull request by erciccione**
The preprint has been withdrawn (https://eprint.iacr.org/2020/312), commenting it out until it's reuploaded or a new source is provided. Or maybe we should remove it completely? @SarangNoether?

### CODE REVIEW

**Comment by SamsungGalaxyPlayer** [comment]
Would it be better to start with `RETRACTED:`?

**Comment by erciccione** [comment]
don't know if it worth it, since users would be able to only read the introduction, without having access to the paper.

**Comment by selsta** [comment]
> without having access to the paper.

It is still possible to read the paper by clicking on "All versions of this report"

**Comment by erciccione** [comment]
> It is still possible to read the paper by clicking on "All versions of this report"

Then definitely makes more sense to just add a note.

**Review by selsta — APPROVED** [review]

**Pull request merged**
