### PR TITLE
New section and, website, grammar question

### PR DESCRIPTION
**Pull request by davidlatapie**
Added Goods after discussion with fluffypony
Added cryptonit.net under this section
Used the esperanto form of monero. This has implication, because so far we avoided the matter of choosing because we avoided the plural. This doesn't mean only English plural or only Esperanto plural is accepted - both could, like both color and colours are accepted. Still, style-wise, it is better to stick to one word (color everywhere or colour everywhere) so this question still remains for -s vs -j.

### CODE REVIEW

**Comment by fluffypony** [comment]
Why not use it as an adjective for this?

"Physical Monero coins"

**Comment by davidlatapie** [comment]
Yep, forgot there is no plural for adjective in English. This only postpone the matter though (not that I have problem with postponing - urgent first, less urgent later).
We shall mention Bitcoin coins too, we should not filter the content that a website sell (as long as it is legal, of course)

"Physical Monero and Bitcoin coins"

**Comment by fluffypony** [comment]
My personal opinion is that a plural can be skipped completely:

- "That'll be 5 Monero, sir"
- "How many Monero do I owe you?"
- "They sell Monero on Poloniex"
- "The vast quantity of Monero available"

I can't (yet) think of a sentence where plurality is necessary.

**Comment by davidlatapie** [comment]
Don't we say "That'll be 5 dollars, sir"?

/me thought he understands English plural

**Comment by fluffypony** [comment]
Yes we do, but not every currency name behaves like that. Take French Francs, for example:-P

A better example is the Yen. We don't say "that'll be 5 Yens, sir", we just say "that'll be 5 Yen, sir", and then karate-chop them into oblivion.

**Comment by davidlatapie** [comment]
OK so let's go with Physical Monero and Bitcoin coins (ugly "coin-coin" here, but Monero has to be first!)

**Comment by fluffypony** [comment]
Sounds good - if you make the changes to your patch-5 branch and push them then this PR will update and I can merge it

**Comment by davidlatapie** [comment]
Seems to be done. I'll wait confirmation before closing, though.

**Comment by fluffypony** [comment]
Perfect:)

**Pull request merged**
