### PR TITLE
devguides: add subtract_fee_from_outputs to wallet-rpc transfer

### LINKED ISSUE #2248: devguides: wallet-rpc transfer amount with fee included missing
https://github.com/monero-project/monero/commit/b4eb3f18340e04583d66324f33a97947666016b5

### PR DESCRIPTION
**Pull request by plowsof**
blocked until next release 

closes #2248

### CODE REVIEW

**Comment by jeffro256** [comment]
The word "proportionally" here might be misleading. The feature splits the fee evenly between the destinations flatly, i.e. regardless of destination amount.

**Comment by plowsof** [comment]
Thanks @jeffro256, something like this: ?
>The fee will be subtracted evenly from each destination (regardless of amount).

Thoughts on this warning or is it dumb
>Do not use this if recipient requires an exact amount.

**Comment by jeffro256** [comment]
No that would be a good warning to put IMO. Also latest commit looks good

**Comment by plowsof** [comment]
docs are moving to https://github.com/monero-project/monero-docs

merged in https://github.com/monero-project/monero-docs/pull/67

closing. thank you

**Pull request closed without merging**
