### PR TITLE
Add kovri channels to hangouts page

### PR DESCRIPTION
**Pull request by el00ruobuob**
This solves #742.
Actually Work In Progress as it is useless to update hangout page while @rehrar is reworking it for multilanguage reimplementation.

### CODE REVIEW

**Comment by el00ruobuob** [comment]
After checking on a local rebase onto #744, it does not need further changes. I'll test it.

**Comment by el00ruobuob** [comment]
So far so good:
image

**Comment by el00ruobuob** [comment]
ping reviewer @anonimal

**Comment by el00ruobuob** [comment]
ping @rehrar & @luigi1111 Could we merge this?

**Comment by anonimal** [comment]
Thanks @el00ruobuob

**Pull request merged**
