### PR TITLE
Add noreferrer + noopener attributes to blank targets

### PR DESCRIPTION
**Pull request by anonimal**
Increases privacy by requiring supported browsers to *not* send a
referer header. Also prevents tabnabbing.

### CODE REVIEW

**Comment by anonimal** [comment]
@MaxXor AFAICT, tabnabbing works with `same-origin` and `cross-origin` policies, and we would still need `noopener`. What's your solution exactly?

**Comment by MaxXor** [comment]
You are right, I forgot tabnabbing. Not sure if a simple http header can fix it for external URLs.

**Comment by fluffypony** [comment]
Please rebase

**Comment by anonimal** [comment]
@fluffypony rebased.

**Pull request merged**
