### PR TITLE
Add Coin Wallet

### PR DESCRIPTION
**Pull request by nikashitsa**
This PR adds [Coin Wallet](https://coin.space/) to Downloads section.

### CODE REVIEW

**Review by erciccione — CHANGES_REQUESTED** [review]
The wallet seems to be at least partially open source (a deeper investigation would be needed), but personally, i don't know it and i don't think it's estabilished and trusted enough to be listed on the Downloads page.

NACK

**Comment by nikashitsa** [comment]
Hi @erciccione, Coin Wallet is non-custodial crypto wallet.

Main repo is here: https://github.com/CoinSpace/CoinSpace
Client code is completely open source. Links to monero part:
- https://github.com/CoinSpace/cs-monero-wallet
- https://github.com/CoinSpace/monero-core-js
- https://github.com/CoinSpace/monerolib

Backend is partially private like in MyMonero.

Please let me know if you need more details about Coin Wallet ;)

**Comment by erciccione** [comment]
Thanks for the info @nikashitsa. Good to know the wallet is non-custodial and fully open source. I still think it's not estabilished enough to be listed in the downloads page.

**Comment by nikashitsa** [comment]
@erciccione why do you think so? Perhaps, we could improve something in order to get listed?

**Comment by erciccione** [comment]
You cannot. We list only trusted wallets on the Downloads page. Your wallet is not estabilished and trusted enough to be listed. That's why I NACKed it. Others might have a different opinion.

**Comment by selsta** [comment]
@nikashitsa how long does coin wallet with monero support exist?

**Comment by nikashitsa** [comment]
@selsta monero support has been added on 1st July 2021 (https://github.com/CoinSpace/CoinSpace/releases/tag/v4.0.0).

**Comment by selsta** [comment]
@nikashitsa I hope you can understand that we are careful with listing wallets on getmonero.org, especially if the wallet is new.

See a list of wallets here (https://www.reddit.com/r/Monero/comments/ohdx47/rmonero_weekly_discussion_july_10_2021_use_this/) and compare it with the ones on getmonero.org – we currently only list a small amount on the website.

You can reach out to the Reddit mods to get your wallet added to the weekly discussion post.

**Comment by nikashitsa** [comment]
@selsta I understand. Thank you for the link 😊

**Comment by erciccione** [comment]
Closing this.

**Pull request closed without merging**
