### PR TITLE
update website tech, Astro soon

### PR DESCRIPTION
**Pull request by jermanuts**
Soon! Merge when live website is rebuilt in Astro.

### CODE REVIEW

**Comment by nahuhh** [comment]
NACK

tl strings change with astro

**Comment by plowsof** [comment]
re-open after astro conversion is done. i might even NACK this based on the commit history leading to confusion of who made the conversion.

**Comment by jermanuts** [comment]
I made it a draft, won't probably cause a confusion as the PR for Astro conversion will be probably called something like "convert website to Astro"

**Comment by plowsof** [comment]
The structure of files (especially translation) is going to change. 

It's possible there wont even be file named `_i18n/en.yml`. keeping this PR open, even as a draft, and showing any approval could cause the team working on the new astro site emotional distress thinking they are required to create a merge request that blends into current master branch. 

Add your changes to the astro site / branch where development is taking place. not here. 

There may also be an onus on the current site maintainer to adapt all PR's made to the "future astro" site and handle merge conflicts. For this particular PR it would all be because of a 1 word patch.

**Pull request closed without merging**
