### PR TITLE
Monero Addresses Cheatsheet for library section

### PR DESCRIPTION
**Pull request by baro77**
I propose for Monero documentation a cheatsheet I have written to consolidate my own knowledge

### CODE REVIEW

**Comment by erciccione** [comment]
The PDF is clean according to [VirusTotal](https://www.virustotal.com/gui/file/e2fb4944119f675da6600c5ef7b903ecffa130f17fb4c7f6c12a59a8e8d126ff/detection). I asked people of the MRL to take a look. Waiting for a review.

Screenshot of the content:

Screenshot from 2020-12-03 13-49-05

**Comment by baro77** [comment]
Thanks! I will appreciate any suggestions/review to improve it

**Comment by UkoeHB** [comment]
Pretty sure 'Twisted Edwards' is actually 'twisted Edwards' (see a real source)[https://eprint.iacr.org/2008/522]. This is a mistake I made in ZtM2

**Comment by baro77** [comment]
Thanks for the corrections Koe! I'm going to wait a couple more days looking for other suggestions as well, then I'll update the cheatsheet content and its version... btw, what's the best way to provide the project with the update? A new PR updating description and link in Library page as well, or just attaching the new PDF to this thread?

**Comment by erciccione** [comment]
> btw, what's the best way to provide the project with the update?

Are you referring to Zero to Monero or to this repository? If the latter, you can just update this PR with the updated PDF.

**Comment by baro77** [comment]
Hi! I think I have implemented Koe's suggestions, and a couple of minor improvement in words choice:

- fixed typos: Twisted -> twisted, technic -> technique
- replaced misguiding reference to EdDSA with reference to EC points' cyclic nature 
- removed citation of EC order, not being able to detail about "l" and "cofactor"
- in "Diffie-Hellman" grey ballon, replaced word "nature" with "connection"
- in cheatsheet description tag, replaced "mathematical rigor" with "mathematical details"
- update cheatsheet version, file name and -consequently- links and tags names

**Comment by baro77** [comment]
Hi guys! Hope Christmas is great for everyone.
I'm writing 'cause this PR is silent since my last commits 3 weeks ago so I was wondering if there's something else I can/must do.
If I just have to wait without breaking the silence... well sorry for this post :) 
See ya!

**Review by UkoeHB — APPROVED** [review]

**Review by erciccione — APPROVED** [review]
Needs to be merged and squashed

**Comment by baro77** [comment]
> Needs to be merged and squashed

Squashed!

**Review by erciccione — APPROVED** [review]

**Pull request merged**
