### PR TITLE
downloads: add nano s plus firmware

### PR DESCRIPTION
**Pull request by selsta**
I have no idea what I'm doing and why these are even translatable strings in the first place...

### CODE REVIEW

**Review by erciccione — CHANGES_REQUESTED** [review]
Changes should be done only for the English file (`en.yml`).

I don't remember why i had decided to add those as translatable strings (maybe for consistency), but i would be ok with taking them out of the language files.

**Comment by selsta** [comment]
@erciccione do I have to take them out of the english one only? or all?

**Comment by erciccione** [comment]
Sorry for the confusing wording. They should be only removed from the English file. As a general rule, we shouldn't touch non-english language files.

**Comment by selsta** [comment]
#2034

**Pull request closed without merging**
