### PR TITLE
View-only wallet guide: update instructions + create from private view key in GUI

### PR DESCRIPTION
**Pull request by rating89us**

### CODE REVIEW

**Review by erciccione — COMMENTED** [review]
The snippet on the top of the guide for every other language will need to be changed to `{% include disclaimer.html translated="no" translationOutdated="yes" %}`. Could you do that? Otherwise i'll do it in another PR.

**Comment by rating89us** [comment]
Updated

**Comment by erciccione** [comment]
Sorry, i got confused. The snippet should be changed to `{% include disclaimer.html translated="yes" translationOutdated="yes" %}` if the guide was already translated in that language (so if `translated="yes"`). If the guide isn't translated, you can simply copy paste the new guide and replace the old one (keeping the snippet as it is: `{% include disclaimer.html translated="no" translationOutdated="no" %}`

**Comment by rating89us** [comment]
Updated

**Review by erciccione — APPROVED** [review]
Looks good. Thanks :)

**Pull request merged**
