### PR TITLE
merchants: remove actio-fast-pay.net

### LINKED ISSUE #1517: REMOVE scammer actio-fast-pay.net from the list of merchants
#### What's the name of the business?

actio-fast-pay.net

#### What's the URL of the website?

actio-fast-pay.net

#### Write a brief description of your business/service (max 50 characters)

I sent well over the minimum required XMR (>3.5 XMR) to actio-fast-pay.net in exchange for BTC. After 21 confirmations I still haven't received my BTC. Their website claims their support responds in 15 - 60 minutes but I haven't heard back from them at all after two seperate emails. I was scammed out my XMR. 

#### Comment

I'm deeply saddened by how little due diligence was done before listing this exchange to the official Monero website. See [Issue 1388](https://github.com/monero-project/monero-site/issues/1388) for what I'm referring to. If there's any way that someone knows if how I can recover my XMR please let me know.

### PR DESCRIPTION
**Pull request by erciccione**
I received a detailed complaint about this company, from somebody who lost money using their website. They do seem to be scammers. Removing them from the list.

It was added with #1388.
closes #1517

### CODE REVIEW

**Review by wirrickelliot — APPROVED** [review]

**Comment by danvctr** [comment]
Just opened Issue 1517 because I was scammed by this site. 

This is truly unacceptable that this exchange was listed in the first place. I just lost a majority of the XMR I purchased 3 years ago, well over $1k, because of the lack of due diligence here. 

I clearly should have done more research on my end before trusting this website, but since it was listed as an official exchange I made the mistake of trusting the reputation I had for the official Monero website.

**Comment by danvctr** [comment]
If you have any XMR to spare, consider sending it along to 88apaEzvWfXUo71qSxKiWLWWTUFfc4pLYMWh8RuydCscNFAzsGVeRuY5TQU4ofJ2LvKExEcahCumd5X5fG7LoUUtQpwhv5J

Feel free to remove this as it probably violates your guidelines, but I'm definitely feeling like I'm at a low point here...

**Comment by actio-fast-pay** [comment]
> If you have any XMR to spare, consider sending it along to 88apaEzvWfXUo71qSxKiWLWWTUFfc4pLYMWh8RuydCscNFAzsGVeRuY5TQU4ofJ2LvKExEcahCumd5X5fG7LoUUtQpwhv5J
> 
> Feel free to remove this as it probably violates your guidelines, but I'm definitely feeling like I'm at a low point here...

You did not create an exchange transaction with us, and the transaction you specified is not related to our service!

**Comment by actio-fast-pay** [comment]
> I received a detailed complaint about this company, from somebody who lost money using their website. They do seem to be scammers. Removing them from the list.
> 
> It was added with #1388.

Please do not delete our service because this is a dirty provocation of the user, he did not create our deal for the exchange, we did not receive immediate notice of the exchange that the user opened a discussion here, as soon as we saw that here we were accused of fraud, we were surprised by this and immediately described the situation in Issue.
Please remove the user's filthy provocation as what he writes is not true.

**Comment by actio-fast-pay** [comment]
> I received a detailed complaint about this company, from somebody who lost money using their website. They do seem to be scammers. Removing them from the list.
> 
> It was added with #1388.

Please do not delete our service because this is a dirty provocation of the user, he did not create our deal for the exchange, we did not receive immediate notice of the exchange that the user opened a discussion here, as soon as we saw that here we were accused of fraud, we were surprised by this and immediately described the situation in Issue.
Please remove the user's filthy provocation as what he writes is not true.

**Comment by actio-fast-pay** [comment]
We suspect that this is the action of unscrupulous competitors, because we have not had any complaints from our users. And this complaint is just a text written by a user without any proof, so they can blame any service and remove all unwanted ones from the merchant list.

**Pull request merged**
