### PR TITLE
[CoinGecko] Add backlink to CoinGecko website

### PR DESCRIPTION
**Pull request by ervinchai**
# Overview
Hello there! I'm Ervin from CoinGecko. Recently, our team has reached out to you to implement backlinks on the Monero website (`getmonero.org`). This PR is an implementation of those requests. Please let me know if you need me to verify my identity, or if you require any thing else from my end. I would be happy to provide you with any information you require!

# Description
Adds backlinks to CoinGecko.com website.

# Changes
- Add CoinGecko link on Community footer.
- Add CoinGecko link to XMR exchanges on the Merchants & Exchanges page (CEX section)

# Screenshots & Recordings

| Description | Image/Recording |
| --- | --- |
| On the footer | image |
| On the Markets & Exchanges page (CEX section) | image |

### CODE REVIEW

**Comment by erciccione** [comment]
Hi @ervinchai thanks for opening this PR, but i'm a bit confused. Who did you speak to about adding these changes?

My personal opinion:

> Add CoinGecko link on Community footer.

The footer currently strictly contains only monero-related resources. I don't think a link to coingecko fits there.

> Add CoinGecko link to XMR exchanges on the Merchants & Exchanges page (CEX section)

I do not agree with this change and i don't see it necessary. Beside, we could end up with all price browsers/aggregators around requesting to be added to getmonero, for unclear benefits if any.

**Review by erciccione — COMMENTED** [review]
Hi @ervinchai thanks for opening this PR, but i'm a bit confused. Who did you speak to about adding these changes?

My personal opinion:

> Add CoinGecko link on Community footer.

The footer currently strictly contains only monero-related resources. I don't think a link to coingecko fits there.

> Add CoinGecko link to XMR exchanges on the Merchants & Exchanges page (CEX section)

I do not agree with this change and i don't see it necessary. Beside, we could end up with all price browsers/aggregators around requesting to be added to getmonero, for unclear benefits if any.

**Comment by fluffypony** [comment]
@erciccione they spoke to me - I suggested they put it in a PR so it could be reviewed and discussed.

FWIW I'm a big fan of this, as there is WAY more data on exchanges on CoinGecko (eg. volume, trustworthiness of the data, trading pairs) than we'll ever display on the site.

I also think that (generally speaking) CoinGecko has become the de facto destination for anyone wanting to get information on a particular cryptocurrency / token, even moreso than CMC.

**Comment by fluffypony** [comment]
FWIW I view this similarly to the Merchants section - we used to have this long listing that was basically impossible to maintain. Nowadays we link out to cryptwerk and acceptedhere, because it's not our job to maintain a list of every Monero-accepting merchant any more than it's our job to maintain a list of every exchange that has a Monero pair.

**Comment by erciccione** [comment]
Thanks for the clarification @fluffypony.

I'm still against listing coingecko in the footer, but if people are ok with listing aggregators like coingecko on getmonero, the format suggested in this pr needs to be revisited in favour of a more neutral approach, where more aggregators can be listed.

For context, this is the PR that revamped the merchants page, removing the link to single merchants in favour of lists we don't need to maintain: https://github.com/monero-project/monero-site/pull/1743.

If people accept listing aggregators like coingecko on getmonero, my suggestion is to make sure the list is going to be maintained, which is the problem we had before and that we still have, even if partially, since not all directories were removed.

**Comment by nahuhh** [comment]
Against.

**Comment by HardenedSteel** [comment]
We should remove CEX list especially Binance since they're very untrustworthy for Monero.

But on Coingecko these exchanges have green trust score even the community suggested remove these exchanges from Coingecko's Monero page on Reddit but moderators decided to censor it and remove [the post](https://redd.it/u3fr32/) [[archive]](https://www.unddit.com/r/coingecko/comments/u3fr32/binance_huobi_and_poloniex_should_be_excluded/) (while their subreddit is spammed with scam coin advertisements and mods don't care about it.)

As @nahuhh said, kycnot.me would be better option.

**Comment by HardenedSteel** [comment]
We should remove CEX list especially Binance since they're very untrustworthy for Monero.

But on Coingecko these exchanges have green trust score even the community suggested remove these exchanges from Coingecko's Monero page on Reddit but moderators decided to censor it and remove [the post](https://redd.it/u3fr32/) [[archive]](https://www.unddit.com/r/coingecko/comments/u3fr32/binance_huobi_and_poloniex_should_be_excluded/) (while their subreddit is spammed with scam coin advertisements and mods don't care about it.)

As @nahuhh said, kycnot.me would be better option.

**Comment by nahuhh** [comment]
@ervinchai 

XMR is so private it seems to be hiding in the awkward empty space next to.. YFI. Need to use a font that is visible to the naked eye 👻.
Also, XMR should be first on this list, not last. I'm serious.

Thanks!

**Comment by erciccione** [comment]
Asked for more feedback on #monero-site. Current consensus seems to be for rejecting the PR, but we have only 2 feedbacks so far (excluding my alternative).

**Review by erciccione — COMMENTED** [review]
Asked for more feedback on #monero-site. Current consensus seems to be for rejecting the PR, but we have only 2 feedbacks so far (excluding my alternative).

**Comment by SamsungGalaxyPlayer** [comment]
I'm okay with CoinGecko being linked in the Merchant page, but not the footer

**Review by erciccione — COMMENTED** [review]
Consensus seem to be to reject this PR. @ervinchai please edit this pr to add coingecko to the merchant page only or open a new PR.

**Comment by erciccione** [comment]
ping @ervinchai

**Comment by erciccione** [comment]
Closing as there was no reply. Feel free to open another PR to add coingecko to the Merchants page

**Pull request closed without merging**
