### PR TITLE
Added Haveno, removed Localmonero

### LINKED ISSUE #2304: Add Haveno.exchange in P2P exchanges and Atomic Swaps and remove the localmonero
In the menu under the > Community > Merchants & Exchanges > P2P exchanges and Atomic Swaps to add Haveno.exchange include the link to there website as it now the only nonkyc fiat to xmr on and off ramp. Then subheading inside the Haveno.exchange a list of the haveno networks which is currently live and working network:
Haveno-Reto network and a link to there github page:

https://github.com/retoaccess1/haveno-reto

Also need to remove localmonero as has shutdown

### PR DESCRIPTION
**Pull request by ligix**
Title is self explanatory, this PR replaces Localmonero with Haveno in `Community > Merchants & Exchanges > P2P exchanges and Atomic Swaps`.

Closes #2304

### CODE REVIEW

**Comment by Justxd22** [comment]
replace logo with svg [[logo]](https://raw.githubusercontent.com/haveno-dex/haveno-meta/721e52919b28b44d12b6e1e5dac57265f1c05cda/logo/haveno_logo_landscape.svg)

**Comment by ligix** [comment]
>We should.consider leaving it up and displaying the above timeline for 6 months with the deletion coming after as this may help someone
>~ plowsof

Looking at #2293, how should it be handled?

IMO if you want to keep linking Localmonero it may make sense to just push it to the bottom of the list since the roadmap is displayed prominently on the homepage of Localmonero.
It could also be grayed out / a warning could be shown in the description but at that point what's the point of keeping it linked?

Screenshot showing an alternate description for Localmonero which has "⚠️ Shuts down on November 7 2024 ⚠️" appended to it

**Comment by plowsof** [comment]
> replace logo with svg [[logo]](https://raw.githubusercontent.com/haveno-dex/haveno-meta/721e52919b28b44d12b6e1e5dac57265f1c05cda/logo/haveno_logo_landscape.svg)

i thought we had established svg's should be replaced from getmonero https://github.com/freedomofpress/securedrop/issues/1574#issuecomment-279068270

**Comment by plowsof** [comment]
I also NACK at this moment in time for listing haveno.exchange on the merchants/p2p section. it's mostly info / a blog.

**Comment by ligix** [comment]
> I also NACK at this moment in time for listing haveno.exchange on the merchants/p2p section. it's mostly info / a blog.

Sure, I'll close this until it's more mature.

**Pull request closed without merging**
