### PR TITLE
Add banner for October 2020 network upgrade

### PR DESCRIPTION
**Pull request by erciccione**
I changed a bit the structure and added useful links. ~~Now the banner appears on all pages, not only the home.~~

### CODE REVIEW

**Review by 00-matt — CHANGES_REQUESTED** [review]
Sorry to be so picky, but could we increase the contrast of the text in the banner? My eyes aren't so good, and I'm colourblind so it's almost unreadable for me unless I select/highlight the text. I think the CSS needs to change `.upgrade-content` and `.upgrade-content a`.

**Comment by erciccione** [comment]
@00-matt That's not picky, thank you for letting me know. I increased the contrast until we reached the AAA rate in the WCAG scale. Let me know if it's ok now. I took the chance to also improve the CSS a bit.

**Comment by 00-matt** [comment]
Thanks :) Just waiting for Netlify to rebuild.

**Review by 00-matt — APPROVED** [review]

**Comment by erciccione** [comment]
The banner is only on the homepage now.

**Review by selsta — APPROVED** [review]

**Pull request merged**
