### PR TITLE
Delete README.md

### PR DESCRIPTION
**Pull request by leonklingele**
# *This repository has moved, PLEASE do not open a pull request here!*

You can, instead, open a pull request on the self-hosted GitLab instance at: https://repo.getmonero.org/monero-project/monero-site

- [x] I have read the above message
- [x] Despite reading the above I've ignored it
- [ ] I understand that if I open a PR it'll just be closed
- [ ] But I'm a total idiot
- [x] Because of the above I'm opening a pull request anyway

### CODE REVIEW

**Comment by leonklingele** [comment]
Will this be closed automatically?

**Comment by el00ruobuob** [comment]
I opened a PR on the repo that has already be merged and inform users about the move. This repo should soon be sync with repo.getmonero.org, so the updated readme will be visible.

**Comment by lh1008** [comment]
Great, congrats! We need to move ourselves :).

**Comment by BlackLotus64** [comment]
Great, I think those are good news, see you there guys.

**Comment by leonklingele** [comment]
I was just testing wether this issue would be closed by a bot or something. Doesn't look like it (yet).

**Comment by erciccione** [comment]
@sneg55 Did you try to log in using a github account or a  brand new one on gitlab?

**Comment by sneg55** [comment]
> @sneg55 Did you try to log in using a github account or a brand new one on gitlab?

Thanks, it works now when I created a new account on gitlab instead of github oauth.

**Pull request closed without merging**
