### PR TITLE
Add compressed RingCT video

### LINKED ISSUE #435: Add RingCT Video to media
https://github.com/monero-project/monero-site/tree/master/media

The RingCT video should be added so that it can be used in the website.

Video: https://www.youtube.com/watch?v=M3AHp9KgTkQ

### PR DESCRIPTION
**Pull request by SamsungGalaxyPlayer**
Adds a compressed RingCT video.

Resolves #435.

### CODE REVIEW

**Comment by mattcode55** [comment]
I think you'd want to squash the commits into one.

If you've commited in the uncompressed video and the compressed video, they'll both be in the history taking up space.

**Comment by fluffypony** [comment]
@mattcode55 is correct - makes the git history huge, plz squash

**Comment by luigi1111** [comment]
@SamsungGalaxyPlayer ping

**Comment by SamsungGalaxyPlayer** [comment]
I need to learn how to do this. I will do it though.

**Comment by SamsungGalaxyPlayer** [comment]
@luigi1111 I finally squashed these :)

**Comment by mattcode55** [comment]
I think the video needs embedding too :)

Should it go in a new carousel slide in `get-started/what-is-monero/index.md`?

**Comment by SamsungGalaxyPlayer** [comment]
@mattcode55 yes, it needs to be embedded too. Can you open a new PR for that please?

**Comment by mattcode55** [comment]
@SamsungGalaxyPlayer Does the thumbnail in #521 look okay?

**Pull request merged**
