### PR TITLE
Cosmetics of the "what-is-monero" page

### PR DESCRIPTION
**Pull request by qertoip**
* Remove end-of-sentence dots from the h3 titles on the what-is-monero page for consistency with other articles.
* Replace "unbreakable cryptography" with "strong cryptography" to not put off the expert readers.

### CODE REVIEW

**Comment by qertoip** [comment]
The most important thing here is really replacing the "unbreakable" with "strong" to make it 1) right and 2) consistent with Monero's no-bullshit sound technical narrative.

**Comment by fluffypony** [comment]
Please rebase

**Comment by qertoip** [comment]
Rebased.

**Comment by fluffypony** [comment]
@qertoip sorry I merged something else that messed up your rebase, sincere apologies. Can you re-rebase?

**Comment by fluffypony** [comment]
@qertoip ping

**Comment by rehrar** [comment]
@qertoip I'd love to have this included. :) Can you rebase it?

**Comment by el00ruobuob** [comment]
Is this PR still alive? Or even needed in it's actual form?
I mean, all the translations are now showing the unnecessary dots, everything is now in _i18n folder, the html typos (missing end of kovri paragraph) has been corrected.
It should be redone, based on this one, but on actual site structure to:
- remove the dots on all languages ;
- place the kovri link on kovri itself, and not at the currently in development level.

Just say the word and i build a new, up-to-date, PR for those.

**Pull request closed without merging**
