### PR TITLE
Repo: add Vulnerability Response Process

### PR DESCRIPTION
**Pull request by anonimal**
As discussed in Kovri meetings, IRC, https://github.com/monero-project/monero/pull/1995, https://github.com/monero-project/monero-core/pull/778, and https://github.com/monero-project/meta/issues/39: here is a formalized VRP. This VRP will aid us in working with researchers and HackerOne.

RFC, WIP.

### CODE REVIEW

**Comment by fluffypony** [comment]
Needs to be added into the correct location and linked from somewhere. Maybe in /knowledge-base/ or something. Or, better yet, let's close this and have @rehrar add it to the new site.

**Comment by anonimal** [comment]
>Or, better yet, let's close this and have @rehrar add it to the new site.

I'd prefer to keep the git-log intact. Sidenote: the same goes for any contributions to his site copy repo.

JFTR: this VRP applies only to monero-site and kovri-site. There are a few lines between this VRP and monero/monero-core/kovri's. If this VRP is posted to the site, it should be noted that it *only* applies to the site.

>Needs to be added into the correct location and linked from somewhere. Maybe in /knowledge-base/ or something.

I've linked all VRP's on policies page at hackerone.com/monero. Perhaps we can do this to monero-site as well. As for this PR, I imagined it not going live but rather being a repo-only markdown file but I can move it to knowledge-base for the time being.

**Comment by anonimal** [comment]
12c2ed2 pushed for review, @fluffypony.

**Comment by jonathancross** [comment]
@anonimal Needs rebase

**Comment by fluffypony** [comment]
@anonimal still pending rebase plx

**Comment by anonimal** [comment]
I think on average I get ~20-30 github notifications every day so this one slipped by the wayside.

The site design as changed since original PR and https://github.com/monero-project/monero-site/pull/282/commits/7d77f3284c560889b7a62ce13b69ee36c58d014e is not producing a link in the Resources dropdown. Why?

**Comment by rehrar** [comment]
You will get it on mobile. There are two navigations that display based on different screen widths. Every new page needs to be added to both the mobile and desktop navigation. You just added it to mobile.

**Comment by anonimal** [comment]
None of this is noted in the README...

**Comment by rehrar** [comment]
The README that is currently posted was made for how a regular person wanting to add the normal things will be able to do so (blog posts, User Guides, etc.). A regular person should not be adding entire pages without thorough review and approval, so it was not included in the README.

If it is expected for me to put how to change this sort of thing in the README then I can add it, although I would not recommend it myself.

**Comment by anonimal** [comment]
You shouldn't assume, nor define, a "regular person". Just make good docs if you want people to contribute - and not have them waste time trying to figure out how.

**Comment by anonimal** [comment]
@fluffypony rebased. I shortened "Vulnerability Response Process" to "Vulnerability Response" as a hack to keep text inside the dropdown.

**Comment by anonimal** [comment]
The reason why I did not want to put this on the website, and instead keep it within the repo, is because now the end-user question is "does this VRP apply to monero-site or monero?".

I think adding both the website and monero repo VRP, and pointing out which-is-which, would be prudent. How does that sound?

**Comment by fluffypony** [comment]
@anonimal we can always expand it if necessary.

**Pull request merged**
