### PR TITLE
Add post about MoneroKon

### PR DESCRIPTION
**Pull request by ajs-xmr**

### CODE REVIEW

**Comment by ajs-xmr** [comment]
Note, links to YouTube are canonical. The [Monero Community Workgroup](https://www.youtube.com/@MoneroCommunityWorkgroup) channel has hosted Monero-related content since 2017.

**Comment by nahuhh** [comment]
My 2c

We should not be endorsing "Monero"Kon or posting blogs about conferences that prefer to hold fiat / eth stables, run hackathons for zano, don't reimburse speakers travel (yet subsidize student tickets), reject sponsors, and have terrible accounting. 

attendees may enjoy monerokon, but the conference is a sham. Last year was questionable, and this year looks to be even more loosely related to / less focused on monero.

Monero standard, monero.observer, moon, revuo are the correct places for such "news".

**Comment by ajs-xmr** [comment]
Thanks for the thoughtful and eloquent feedback @nahuhh However, I would have to push back against your characterization of the event and point out inaccuracies.

> that prefer to hold fiat / eth stables

MoneroKon 2022 and 2023 was organized using an LLC, with a director from Monero core team, and they preferred keeping the books in fiat for simplicity and avoid issues with bank freezing accounts for dealing with crypto. The LLC was necessary to contract with venues and suppliers. The LLC controlled all the funds and paid invoices according to community consensus in voting for or against invoices during planning meetings held in #monero-events. The LLC provided this service to the community for free [1](https://repo.getmonero.org/monero-project/ccs-proposals/-/merge_requests/362).

For MoneroKon 2024, community members decided to form a non-profit association for the conference and we now have more direct control over funds. We have been operating mostly in crypto without a bank account, using crypto-to-fiat services to pay invoices. 

We do hold a portion of funds in DAI [2](https://app.safe.global/balances?safe=matic:0x22942517e3eDEF1e1016070951a7081F99AE50A3) and majority in XMR [3](https://app.rino.io/public/wallets/mk-fund). Many of our expenses are in EUR/CZK, by having a mixture of crypto assets, we are able to cost average our expenses. In other words, we want to avoid a “Haveno frontend development situation” in having expenses in fiat and revenue in crypto [4](https://ccs.getmonero.org/proposals/haveno-frontend.html).

> run hackathons for zano

We do not “run” anything for Zano. Zano prizes are independently managed and judged by their own community. Same for the MAGIC prize [5](https://monerokon.devfolio.co/prizes). Having partner sponsored side tracks is a common practice in hackathons to help attract more hackers to the event and increase the total prize pool [6](https://guide.mlh.io/general-information/getting-sponsorship/setting-goals). In addition, there are the benefits of cross promotion, exposing Monero tech to developers of other communities, fostering a positive collaborative environment among developers. 

> don't reimburse speakers travel

We have set aside limited funds for reimbursement for speakers travel, but it is opt-in, targeted specifically for students and early career researchers. The majority of speakers have opted to not to request a travel bursary.

Although we would love to offer speakers an all expense paid trip to Prague for a 20-minute talk, we have over 35 speakers and do not have the budget for it. MoneroKon 2024 is the first year to be self-sufficient without burdening the Monero Community Crowdfunding System with a large proposal as in past events and furthermore, we managed to keep ticket prices low, which makes the event more accessible for the general public. 

> reject sponsors

A couple sponsors were rejected in 2023 by majority in vote in #monero-events in accordance with Sponsorship Policy [7](https://github.com/MoneroKon/meta/blob/main/policies/sponsorship-policy.md).

No sponsors were rejected for 2024.

> have terrible accounting

Yes, for 2022 and 2023 accounting was difficult since all funds were controlled by the LLC.

For 2024, as an association, we have contracted with an accountant familiar with handling cryptocurrencies. All our wallets are public, all invoices are reviewed and voted on in weekly planning meetings by the community in #monero-events [8](https://mattermost.monerokon.org/plugins/focalboard/team/7jxzshir6j895kwgu71mdx5xrc/shared/bzhq8yhhqppbgmjta45qqe3uajh/vxi7nidwuo7b47n71ijf8gt9xxw?r=kjy8sfgt4yyai75mmbzboihb6tc).

> conference is a sham

Look at what have delivered over the years, hours of content, and a friendly forum for developers, researchers, cryptographers from Monero and other communities to meet in person and exchange ideas. Look at planned schedule of talks and workshops we have for this year. And all this transparently organized and planned for months by hardworking, unpaid volunteers [9](https://mattermost.monerokon.org/plugins/focalboard/team/7jxzshir6j895kwgu71mdx5xrc/shared/buntcef156pgp7fy6x5oyn33rny/vchn7j3cnkpnmiyczoqcbyizkcy?r=k7drhyrbfygt844ejqb7h58o6dw). I fail to see how anyone could objectively call MoneroKon a “sham”, when it is the most legit community-driven crypto event out there.

> Monero standard, monero.observer, moon, revuo are the correct places for such "news"

These are great outlets, but have low traffic compared to the Monero Project website. We hope with greater exposure of the event, we could get some mainstream coverage from other outlets and help attract more developers/researchers to the event. A net positive for Monero IMHO.

**Comment by sausagenoods** [comment]
Last year was well organized and well received with minor complaints. The community worked to solve these issues this year.

MoneroKon is not a simple meetup. This is a 3 day long conference with talks, workshops, community project/sponsor tables, a hackathon and more. This is the biggest Monero event in EU, and probably the world. Because of its large scale, I think it deserves a post.

**Comment by plowsof** [comment]
we have the `conferences` tag which makes such a post more plausible than i thought

**Comment by selsta** [comment]
I would remove the announcements tag here, since the only time we used this was during the CCS hack and I don't think this is comparable.

Otherwise I don't see an issue with a blog post for MoneroKon.

**Review by SamsungGalaxyPlayer — APPROVED** [review]

**Review by hinto-janai — APPROVED** [review]

**Pull request merged**
