### PR TITLE
Typo in developer-guides.md

### PR DESCRIPTION
**Pull request by el00ruobuob**
Small typo to correct in the English file (as well as the template, and other unfinished translations).

### CODE REVIEW

**Comment by luigi1111** [comment]
@el00ruobuob please rebase instead of merging.

**Comment by el00ruobuob** [comment]
I had a real pain doing it.  Finally i ended push-forcing my master to the original fork, rebasing the branch to it, push-forcing them, and finaly was able to rebase my master to the latest commit without all those glitches. I've learned a lot since yesterday!

**Comment by luigi1111** [comment]
@el00ruobuob :)

You still have 3 commits including a merge commit (only one commit is needed for these changes).

Also there seem to be some gratuitous line break changes at the end of files.

**Comment by el00ruobuob** [comment]
Ok. i corrected the commit and found out atom was adding the trailing newline.

**Comment by luigi1111** [comment]
Thanks for your contributions!

**Pull request merged**
