### PR TITLE
Add 3 new merchants

### LINKED ISSUE #1088: Exchange listing Request
#### What's the name of your business?

Bitvape

#### What's the URL of the website?

https://bitvape.com.au

#### Write a brief description of your business/service (max 50 characters)

Australia's top rated JUUL store. 

#### Enter the URL where a Monero mention can be found

https://bitvape.com.au/we-are-now-accepting-monero-xmr/

#### How do you accept Monero? *(choose only one option)*

MyCryptoCheckout

#### How would you categorize your business? *(choose only one option)*

Goods

#### Comment

I would like to request adding the support for our merchant store. We currently support Monero on our store as mentioned above. Thanks in advance

### LINKED ISSUE #1103: Exchange listing Request
#### What's the name of your business?

Incognito

#### What's the URL of the website?

https://incscan.io/pdex/overview

#### Write a brief description of your business/service (max 50 characters)

Completely anonymous decentralized exchange

#### Enter the URL where a Monero mention can be found

https://incscan.io/pdex/markets/PRV-pXMR
https://incscan.io/shielded-coins/evolution/pXMR
https://we.incognito.org/t/buy-and-sell-monero-xmr-confidentially-without-kyc/415

#### How do you accept Monero? *(choose only one option)*

Native wallet

#### How would you categorize your business? *(choose only one option)*

Exchange

#### Comment

Hello, I would like to request adding Incognito DEX to the getmonero website. We are focused on privacy and working on privacy swap for Monero also we offers 9% APY for liquidity providers. Thanks in advance.

### LINKED ISSUE #1113: New Merchant: monerojobs.com
#### What's the name of your business?

monerojobs.com

#### What's the URL of the website?

monerojobs.com

#### Write a brief description of your business/service (max 50 characters)

The goal of Monero Jobs is to provide a platform for genuine commerce in Monero. Monero Jobs is a job posting service companies can use to hire talent and pay them in Monero.

#### Enter the URL where a Monero mention can be found

https://www.monerojobs.com/donations/donate

#### How do you accept Monero? *(choose only one option)*

- [ ] Monero integrations *(github.com/monero-integrations)*
- [ ] Globee
- [x] Native wallet
- [ ] Other payment gateaway (Coinpayments, Morphtoken, etc. *Please specify*)

#### How would you categorize your business? *(choose only one option)*

- [ ] Exchange
- [ ] Block Explorer
- [ ] Payment Gateway
- [ ] Library and Helper
- [ ] Tool
- [x] Service
- [ ] Goods
- [ ] Entertainment

#### Comment

A job website for the Monero community. Looking forward to working with you.

### PR DESCRIPTION
**Pull request by l33d4n**
- Add MoneroJobs (closes #1113)
- Add Incognito (closes #1103)
- Add Bitvape (closes #1088)

### CODE REVIEW

**Comment by Daniel-Leedan** [comment]
@erciccione Done.

**Comment by ocotopdf** [comment]
@l33d4n Looks like MoneroJobs was removed from the merchants page. Why? Can you please add it back

**Comment by l33d4n** [comment]
@ocotopdf I have no idea why but it looks like @erciccione removed it:

https://github.com/monero-project/monero-site/commit/6597651635b6cc77e7da9a7425c7895bc7a7a690#diff-9f34bbd04e41246051ce150ffb1bc2c95c43ff11e140ba1fd6de741c0555b8c8L263-L264

**Comment by ocotopdf** [comment]
@l33d4n  Thanks for the quick reply. @erciccione can we have that added back?

**Comment by erciccione** [comment]
I must have removed it by mistake. Sorry about that. Fixed with #1395

**Pull request merged**
