### PR TITLE
zero to monero first edition v1.0.0

### PR DESCRIPTION
**Pull request by UkoeHB**
Would like to get this pdf hosted on getmonero.org, for easy and trustworthy access.

### CODE REVIEW

**Comment by MaxXor** [comment]
Thanks a lot for your work! I think a link to your paper should also be included [here](https://getmonero.org/technical-specs/).

**Comment by erciccione** [comment]
@UkoeHB can you squash those 3 commits in just 1?

**Comment by el00ruobuob** [comment]
It looks great. I'll read it when I'll had time.
Do you mind sharing an editable version (markdown would be the best) so that @erciccione team could work on translations and changes could be easily tracked?

**Comment by MaxXor** [comment]
@el00ruobuob The repository is [here](https://github.com/UkoeHB/Monero-RCT-report) and the code is in LaTeX.

**Comment by el00ruobuob** [comment]
Oh my bad. I haven't seen it on GitHub for Android. Great then. Expect to see a French version coming...

**Comment by erciccione** [comment]
Free to translate it if you want @el00ruobuob but the localization workgroup don't have the human resources to take care of the localization of this document at the moment. I prefer to concentrate our translators on other projects.

**Comment by UkoeHB** [comment]
@erciccione how do you squash commits? ive tried researching but cant figure it out.. btw my comp can't run git, so i only have github.com

@el00ruobuob rehrar said he doesnt have time to get this added. Our plan is to add a new page: Library, that can host mastering monero and zero to monero, and whatever else, and link it under Resources on front page. Each book will have a short blurb and direct link to: https://getmonero.org/library/<bookname>.pdf (note: WITHOUT /resources/ so url length is minimized)

Can you, or someone else here, help me get that set up? I can read code ok, but writing it is not my forte.

Once it is set up, the link can be distributed anywhere anyone wants it. I want to go live with a reddit post, and adding it to reddit as a link w/ debruyne's help, and other promotions, as soon as https://getmonero.org/library/zero-to-monero-1-0-0.pdf can load the book.

**Comment by UkoeHB** [comment]
Ok I made all the changes I could figure out. 
-new folder library/
-new library/index.md
-new pdf library/zero-to-monero-1-0-0.pdf
-update /_i18n/en.yml with library title and library text fields
-update /_data/lang/en/footer-1.yml and navigation.yml with links to library

Could someone grab the stuff and make a better pr? these commits are a mess

**Comment by el00ruobuob** [comment]
> @el00ruobuob rehrar said he doesnt have time to get this added. Our plan is to add a new page: Library, that can host mastering monero and zero to monero, and whatever else, and link it under Resources on front page. Each book will have a short blurb and direct link to: https://getmonero.org/library/ bookname .pdf (note: WITHOUT /resources/ so url length is minimized)

I'm on it @UkoeHB & @rehrar.
But rather than "library" i will suggest "bookshop".

**Comment by MaxXor** [comment]
@el00ruobuob I think library is fine. Bookshop implies that it tries to sell something.

**Comment by el00ruobuob** [comment]
@UkoeHB I just saw you updated this PR with the library page added, but there is a few things to discuss:
- You only update the EN yml, i believe it could cause building issues. Did you try building?
- You added a footer link to the page, why not...
- The index page is very static and the yml variable name so generic, i'll suggest been more flexible (like with merchants or irc) on the page and more specific in the yml.
- And as you mentioned it already, there is a lot of glitches.

Are you comfortable with trying to enhance it? Otherwise, i suggest to only add the file in this PR, and i'll come with the new page in another PR, and after discussions on #771 

Btw, it's only my opinion.

**Comment by UkoeHB** [comment]
@el00ruobuob it built fine on my computer. Since it's translated = "no", it seems the other pages display in english. Maybe copy paste into the other files?

The index is simple because its purpose is simple: short description, and a link. I dont think advanced UX will improve user experience here. You can change yml if you want, I didn't think much about it.

**Comment by SamsungGalaxyPlayer** [comment]
I second @el00ruobuob's opinion. It likely makes more sense for @UkoeHB to simply submit the file to the press kit or library page and have other community members handle setting up the rest of the links.

**Comment by UkoeHB** [comment]
Thanks to @el00ruobuob's help, I will close this PR.

**Pull request closed without merging**
