### PR TITLE
Update merchants.yml

### PR DESCRIPTION
**Pull request by poseidonsg**
moneropric.es site is no longer in service.

### CODE REVIEW

**Comment by el00ruobuob** [comment]
Hello @poseidonsg, the repository has been moved to https://repo.getmonero.org/monero-site/ but github still needs to be updated to reflect this. Would you mind creating this pool request on the new repository?

**Comment by poseidonsg** [comment]
I don't have permission to view https://repo.getmonero.org/monero-site/
________________________________

**Comment by el00ruobuob** [comment]
It's an error in my Initial response. Link is https://repo.getmonero.org/monero-project/monero-site

**Comment by el00ruobuob** [comment]
@poseidonsg, are you able to submit your change on the new repo?

**Comment by poseidonsg** [comment]
No. I get a fork error when i try to edit mechants file

[cid:9190e59d-dcb3-40b2-bca9-acc7af856672]
________________________________

**Pull request closed without merging**
