### PR TITLE
Fix: typos in README.md

### PR DESCRIPTION
**Pull request by omahs**
README: fix typos

### CODE REVIEW

**Comment by plowsof** [comment]
Thank you (ideally the commit message would be a bit more relevant to "typos in README.md", it's scary when the translated site pages are touched but this isn't the case here)

**Review by erciccione — COMMENTED** [review]
as @plowsof already said, thecommit message needs to be more specific. Something like "README: fix typos"

**Comment by erciccione** [comment]
ping @omahs

**Comment by omahs** [comment]
@erciccione hey, sorry for the delay, just did it

**Review by plowsof — APPROVED** [review]

**Review by erciccione — APPROVED** [review]

**Pull request merged**
