### PR TITLE
Update merchants.yml

### PR DESCRIPTION
**Pull request by MichaelSelge**
7b crypto trading app added

### CODE REVIEW

**Review by selsta — APPROVED** [review]

**Comment by erciccione** [comment]
@MichaelSelge please open a related issue using the ['New merchant'](https://github.com/monero-project/monero-site/issues/new?assignees=&labels=%F0%9F%8F%AA+merchant%2C+%F0%9F%94%8D+Needs+investigation&template=new-merchant.md&title=Add+%3CNAME+OF+YOUR+BUSINESS%3E+to+the+list+of+merchants) template.

**Comment by erciccione** [comment]
ping @MichaelSelge

**Comment by MichaelSelge** [comment]
Hello @erciccione ! 

Currently we are working on Monero page on our web-site. Should we create new pull request now or when the page will be ready?

**Comment by erciccione** [comment]
If you already accept Monero and want to be added to the Merchants' page, we need you to open an issue and choose the "New Merchant" template. Quick link: https://github.com/monero-project/monero-site/issues/new?assignees=&labels=%F0%9F%8F%AA+merchant%2C+%F0%9F%94%8D+Needs+investigation&template=new-merchant.md&title=Add+%3CNAME+OF+YOUR+BUSINESS%3E+to+the+list+of+merchants. After that issue is created and no problems are found, we can go ahead and merge this PR.

If you don't accept Monero yet, better close this PR and open only the issue when Monero will be supported.

**Comment by MichaelSelge** [comment]
> If you already accept Monero and want to be added to the Merchants' page, we need you to open an issue and choose the "New Merchant" template. Quick link: https://github.com/monero-project/monero-site/issues/new?assignees=&labels=%F0%9F%8F%AA+merchant%2C+%F0%9F%94%8D+Needs+investigation&template=new-merchant.md&title=Add+%3CNAME+OF+YOUR+BUSINESS%3E+to+the+list+of+merchants. After that issue is created and no problems are found, we can go ahead and merge this PR.
> 
> If you don't accept Monero yet, better close this PR and open only the issue when Monero will be supported.

In fact we do accept Monero in 7b - it has been listed for a long time, but we cannot provide any link (which is required according to the "New Merchant" template), because 7b is an app and there is no web-version. If that is possible, I can upload a screenshot from 7b with Monero in it, and add the link to that photo.

**Comment by selsta** [comment]
> If that is possible, I can upload a screenshot from 7b with Monero in it, and add the link to that photo.

That should be fine.

**Comment by MichaelSelge** [comment]
@erciccione @selsta The issue has been made!)

**Comment by erciccione** [comment]
https://github.com/monero-project/monero-site/issues/1692#issuecomment-873182769

**Pull request closed without merging**
