### PR TITLE
merchants: delist Binance [Discussion] 

### PR DESCRIPTION
**Pull request by plowsof**

### CODE REVIEW

**Comment by nahuhh** [comment]
Merge.
relisting plan:
Binance can contact our ceo again to a request an official response to be relisted (when they stop trying to give "us" (who?? Lolz) ultimatums.)

seriously: if they want to be listed, they can open a git issue like everyone else, and they can atop threatening us. L o l

**Review by nahuhh — APPROVED** [review]

**Comment by BTCLovera** [comment]
Merge it!! 

Binance is blacklisted as an exchange that infringes on the privacy, sovereignty and freedom of users.

**Comment by monerobull** [comment]
While we are at it, could we list[ samourais atomic swaps implementation](https://code.samourai.io/wallet/comit-swaps-java/-/releases)? It's way more userfriendly than unstoppableswap which is listed.

**Comment by nahuhh** [comment]
> While we are at it, could we list[ samourais atomic swaps implementation](https://code.samourai.io/wallet/comit-swaps-java/-/releases)? It's way more userfriendly than unstoppableswap which is listed. 

Samourai's impl has had 5 releases in under a week. IMO too early to list it.

maybe need subcategories

exchanges:
- cex (kucoin etc)
- p2p (localmonero, hodl hodl)
- dex (bisq, haveno)
- atomic DEX (basicswap)

swap services:
- Swap Aggregators (trocador, intercambio)
- Custodial Swaps (fixedfloat, changenow)
- Atomic Swaps (unstoppableswaps, samourai)

**Review by luigi1111 — APPROVED** [review]

**Pull request merged**
