### PR TITLE
home: update top card with new slogan and additional button

### LINKED ISSUE #1483: Revise home page top card
The current home page has many lacking attributes. First, the MONERO text is unnecessary. Second, there is no obvious call to action other than "learn more."

The top card should be far more descriptive of Monero and intended for a broader audience. Further, there should be other additional calls to action, most importantly "Join Community."

### Current

image

### Proposed

image

"Join community" will link to https://www.getmonero.org/community/hangouts/ (revision also pending)
"Get Monero" will link to the merchants page for now https://www.getmonero.org/community/merchants/#exchanges
"Lean why it's the standard" will link to https://www.getmonero.org/get-started/what-is-monero/ (revision also pending)

The top card in its current form is not nearly as good as it should be in my opinion.

Related to #1484 #1485 #1486

### LINKED ISSUE #1503: Replace the 'MONERO' header in the homepage with something more informative
As discussed in #1483, the MONERO header inthe homepage is redundant and that valuable space could be used for something with more impact on the visitor.

I think we have three options:

1. Replace the MONERO header with something else and keep 'A private DigitalCurrency' under it
2. Remove both headers and replace them with a 2 different headers.
3. Remove both headers and replaced with 1 single header

What of the three options do you prefer?
What headers(s) should we use?

### PR DESCRIPTION
**Pull request by erciccione**
closes #1483
closes #1503

Preview desktop:
card-desktop

Preview mobile:
top-mobile

### CODE REVIEW

**Comment by Gingeropolous** [comment]
i think "monero is money" might make more sense.

**Comment by erciccione** [comment]
I like "Monero Means Money" more. It's more catchy and it's already around.

**Review by SamsungGalaxyPlayer — APPROVED** [review]
I wish it could not be all caps at the top but this needs to be merged sooner rather than later :)

**Comment by erciccione** [comment]
It was uppercase only on mobile. Fixed now.

**Pull request merged**
