### PR TITLE
Updated roadmap page

### PR DESCRIPTION
**Pull request by sh5x5j12**
Updated roadmap page, added 2021

### CODE REVIEW

**Review by erciccione — CHANGES_REQUESTED** [review]
NACK

This breaks the entire page. The structure does need to be updated though.

**Comment by erciccione** [comment]
Still broken. Please [check the preview](https://github.com/monero-project/monero-site/pull/1423#issuecomment-760967405)

**Comment by sh5x5j12** [comment]
Noooooo. Still there's mistake

**Comment by sh5x5j12** [comment]
damn still there's mistake

**Comment by sh5x5j12** [comment]
> Still broken. Please [check the preview](https://github.com/monero-project/monero-site/pull/1423#issuecomment-760967405)

Hey it looks everything okay right now, can you review again?

**Review by erciccione — APPROVED** [review]
Looks good now. Thanks :)

**Pull request merged**
