### PR TITLE
add moneropedia to po script

### PR DESCRIPTION
**Pull request by netrik182**
this will be later used to update .md, .pot and .po files of both moneropedia and user-guides.

### CODE REVIEW

**Review by erciccione — COMMENTED** [review]
Probably better mention in the comment inside the script that it would work also for the Moneropedia

**Comment by netrik182** [comment]
> Probably better mention in the comment inside the script that it would work also for the Moneropedia

Let me know if it's ok this way and I'll squash my commits.

**Review by erciccione — COMMENTED** [review]
I'd say let's squash and then merge. @netrik182 hasn't been around for some time. If in a week or so the pr is stalling, i'll take care of recovering it.

**Comment by erciccione** [comment]
recovered in #2142

**Pull request closed without merging**
