### PR TITLE
Add P2Pool with XMRig Guide

### PR DESCRIPTION
**Pull request by HardenedSteel**
Change XMRig pool mining guide to p2pool.

### CODE REVIEW

**Comment by nahuhh** [comment]
Nack.. cant just remove pool mining.

p2pool is very expensive for small miners

add p2pool guide, but dont remove pool mining

**Comment by HardenedSteel** [comment]
> p2pool is very expensive for small miners

why so?

**Comment by plowsof** [comment]
> > p2pool is very expensive for small miners
> 
> why so?

Small miners will receive many tiny payouts. Consolidating these these is very expensive as the transaction is large. I do not have the figures off the top of my head atm

**Comment by nahuhh** [comment]
https://github.com/monero-project/monero-docs/pull/44

updated and migrated to docs

**Pull request closed without merging**
