### PR TITLE
Reorganize Monero videos

### LINKED ISSUE #1187: Improve visibility of the videos in the "What is Monero?" page
Some [users report](https://www.reddit.com/r/Monero/comments/iaww0p/getmoneroorg_updated_improved_rss_feed_new/g57j2xq/) they are easy to miss. We could move them somewhere else or make them more visible.

### PR DESCRIPTION
**Pull request by erciccione**
Closes #1187

- Remove carousel structure in the 'What is Monero' page and leave only one video: 'Monero: the essentials'
- Move technology specific videos to their moneropedia entry: Ring Signatures, RingCT, Stealth Addresses
- Add aria-label to imrpove accessibility of the videos

If we like this change, i suggest to also create a FAQ entry saying something like "Are there some videos about how Monero works?" and then link to the videos. They are meant to be watched one after another and this new system kinda break that. I'm proposing it because i don't think people actually notice and watch those videos at the moment. Adding a faq with the list of videos in the right order will fix that and will allow us to link to all the videos at the same time.

We have one video missing here: #1188. We can decide where to put it once we have it.

### CODE REVIEW

**Comment by selsta** [comment]
A lot of unnecessary whitespace on my phone.

IMG_0652

**Comment by erciccione** [comment]
@selsta what browser are you using on mobile? looks good to me using firefox and chromium's mobile previews. No problems on my phone as well.

**Comment by selsta** [comment]
Safari.

**Comment by erciccione** [comment]
Apparently Safari felt free to freak out when the video wasn't contained in a `div` with proper padding. Solved using the same structure used for the Moneropedia videos. I created a dedicated `videos` section in the `GENERAL` CSS section where to put the class used for these videos and I adapted the html accordingly. Everything seem to be working as expected now, on all tested browsers (Firefox, Chromium, Chrome and Safari. Thanks @selsta for helping with Safari).

Ready for reviews.

**Review by selsta — APPROVED** [review]

**Pull request merged**
