### PR TITLE
Update merchants.yml

### PR DESCRIPTION
**Pull request by pwrcycle**
added cloakVPN.com

### CODE REVIEW

**Comment by erciccione** [comment]
Hi, thanks for the contribution, but there is already a [PR](https://github.com/monero-project/monero-site/pull/270) for this

**Comment by pwrcycle** [comment]
I'm not sure what you mean there was already a PR?
I submitted the Pull Request based on FluffyPony's instructions via IRC.
If there's already a PR to add cloakVPN to the merchant page, where can I
see this?

**Comment by serhack** [comment]
Hello pwrcycle,
I have already update merchants.yml with pull request #270 . No one answered me.. :(
Cheers

**Comment by erciccione** [comment]
@pwrcycle     
serhack already proposed the same changes with this pull request: https://github.com/monero-project/monero-site/pull/270    
can you close this? a duplicate just generate confusion.

@serhack 
I guess these minor updates can take a little bit of time before they get merged ;)

**Comment by pwrcycle** [comment]
Closing, duplicate.

**Comment by pwrcycle** [comment]
Why was cloakVPN not included in the latest update of https://getmonero.org/getting-started/merchants

**Comment by erciccione** [comment]
Hi @pwrcycle your VPN is not included because the PR https://github.com/monero-project/monero-site/pull/270 with the changes has not been merged yet, but as you can see from [this](https://github.com/monero-project/monero-site/pull/270/files) link, your vpn is listed in the new file.
Minor updates can require some time, just be patient ;) 
can you close this pr again please?

**Comment by pwrcycle** [comment]
closing, awaiting commit for
https://github.com/monero-project/monero-site/pull/270/files

**Pull request merged**
