### PR TITLE
Add technical specs page

### PR DESCRIPTION
**Pull request by qertoip**

### CODE REVIEW

**Comment by SamsungGalaxyPlayer** [comment]
Should this go at the bottom of the page instead?

**Comment by rehrar** [comment]
Can we take this content and put it in a new page called Coin Specs? There's even a place reserved for it in the footer.

**Comment by QuickBASIC** [comment]
@rehrar I think if it is moved to a new page it should be called `Technical Specifications`.

_Sent from my Google Nexus 6 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by qertoip** [comment]
Thanks to all for the feedback!
* moved to separate page
* linked from the footer
* renamed to "Technical Specs" (the "Technical Specifications" was a bit to long for the links)

**Comment by qertoip** [comment]
Added the "no premine" chapter to directly address this question: https://www.reddit.com/r/Monero/comments/3rya3e/what_are_the_basic_parameterscharacteristics_of/

**Comment by QuickBASIC** [comment]
Given that nature of the cryptocurrency space at the moment, I almost think we should specifically mention that there was no token sale or funding stage as that's specifically a different type of pre-mine and it's something that makes Monero stick out. A lot of people are philosophically opposed to pre-sales, so having that info later might help them make a quicker decision about Monero.

**Comment by qertoip** [comment]
Thanks @QuickBASIC! Please review my attempt to address that. Also added privacy features specs.

**Comment by qertoip** [comment]
Thanks a lot for the approvals. I just made the difficulty retarget more precise by adding "based on the last 720 blocks, excluding 20% of the timestamp outliers".

**Comment by fluffypony** [comment]
Please rebase

**Comment by qertoip** [comment]
Rebased.

**Pull request merged**
