### PR TITLE
devguides: add add_aux_pow to daemon rpc

### LINKED ISSUE #1529: Add add_aux_pow to daemon RPC docs
Added with https://github.com/monero-project/monero/pull/6810

Needs to be included in a release.

### PR DESCRIPTION
**Pull request by plowsof**
closes #1529

### CODE REVIEW

**Comment by erciccione** [comment]
@plowsof what's the status of this pr?

**Comment by plowsof** [comment]
status is i need to figure out (probably ask for help) how to use (what the correct params are) and obtain a valid return.

**Comment by plowsof** [comment]
@erciccione rebased, added correct inputs for a sane output. ready for review

**Review by erciccione — COMMENTED** [review]
Looks ok. Please remove "draft" so can be reviewed and merged.

**Review by erciccione — APPROVED** [review]

**Pull request merged**
