### PR TITLE
Add BitcoinVN

### PR DESCRIPTION
**Pull request by sonofliberty**
I wasn't sure whether to put BitcoinVN under "CEXes" or "Swappers", because it kinda fits both categories.

You can buy and sell XMR for the local currency VND, or any other supported cryptocurrency.

### CODE REVIEW

**Review by erciccione — COMMENTED** [review]
This has been open for quite some time. If there is no feedback within a week or so, i'd close it.

**Comment by lessless** [comment]
Hey @erciccione 
cc @plowsof @binaryFate @selsta @netrik182 

I understand this PR has been open for some time, but I truly believe it would be beneficial for our community to include BitcoinVN in our list of CEX. As the oldest and most reputable exchange in Vietnam, BitcoinVN aligns well with our core principles of individual freedom and sovereignty.

Monero's presence on BitcoinVN would not only expand our reach but also associate us with an exchange that shares our values. Additionally, BitcoinVN has expressed willingness to collaborate in any form to expedite this process.

It's unfortunate that this has taken so long, but I'm confident that the addition of BitcoinVN will bring great value to our community. I appreciate your consideration and I'm available to discuss this further or provide any additional information that might be needed.

Best regards,
Yevhenii

**Comment by plowsof** [comment]
having never personally used the exchange myself i can only say that it seems to have existed since 2017, maybe earlier, twitter profile here https://twitter.com/Bitcoin_Vietnam (joined 2014). and at least promotes 'selling crypto for cash anonymously' per this article https://btm.bitcoinvn.io/.

they specifically list Monero under "Privacy" and I am glad to see that Dash is not included there 
Screenshot from 2023-07-10 14-03-39

It appears to be an instant swapper , Monero can be sent and exchanges for various coins (including BCH/LTC/ETH).

i will send an email to https://kycnot.me/ enquiring about it to perhaps obtain feedback and/or get it added to there also.

**Comment by plowsof** [comment]
Morpheus or trocador.app asks:
> BitcoinVN seems to use Sideshift as an exchange, right?
I wonder how they still have Monero listed
It's featured on Sideshift as a partner and it's the same UI

I await feedback from kycnot.me and intercambio.app

**Comment by sonofliberty** [comment]
Thanks for picking up this issue. Let me address a few questions raised here.

> having never personally used the exchange myself i can only say that it seems to have existed since 2017, maybe earlier, twitter profile here https://twitter.com/Bitcoin_Vietnam (joined 2014). and at least promotes 'selling crypto for cash anonymously' per this article https://btm.bitcoinvn.io/.

Our exchange has been live since 2014, first launched under [bitcoinvietnam.com.vn](https://bitcoinvietnam.com.vn). 

Indeed we take pride in enabling users to withdraw local cash without going through KYC. They can do so either by selling BTC at our BTMs, or with any coin (XMR included) by using one of the [cash pick-up options](https://bitcoinvn.io/?deposit=xmr&settle=vndcashhcmc) on the exchange.
 
> It appears to be an instant swapper , Monero can be sent and exchanges for various coins (including BCH/LTC/ETH).

This is true, however the majority of our exchange volume is tied to our function as a local fiat off- and on-ramp (VND). The KYC-free off-ramp is especially interesting to our Monero users.

>BitcoinVN seems to use Sideshift as an exchange, right? I wonder how they still have Monero listed. It's featured on Sideshift as a partner and it's the same UI

We have integrated with Sideshift and other instant swap exchanges for handling deposits and settlements of various coins we do not otherwise support natively. Monero is not one of those coins, so it continues to work.

**Comment by spirobel** [comment]
>We have integrated with Sideshift and other instant swap exchanges for handling deposits and settlements of various coins we do not otherwise support natively. Monero is not one of those coins, so it continues to work.

just to make that super clear: this means you are a market maker for the XMR/VND pair, right? You hold Monero and VND and don't depend on an external service for that?

**Comment by sonofliberty** [comment]
> just to make that super clear: this means you are a market maker for the XMR/VND pair, right? You hold Monero and VND and don't depend on an external service for that?

Yes, we hold our own inventory of XMR, VND, and most other major coins.

**Comment by lessless** [comment]
Hey @plowsof!

I noticed you were looking into the following:

> Morpheus of trocador.app asks:
> 
> > BitcoinVN seems to use Sideshift as an exchange, right?
> > I wonder how they still have Monero listed
> > It's featured on Sideshift as a partner and it's the same UI
> 
> I await feedback from kycnot.me and intercambio.app

Looks like  most of that sorted out now. Do you think we're good to merge this? 
Just wanted to check in. 

Thanks!

**Review by rbrunner7 — APPROVED** [review]
Prompted by [this recent post](https://old.reddit.com/r/Monero/comments/16jl506/monero_is_on_the_rise_in_vn/) on the Monero subreddit I had a closer look at this PR and BitcoinVN itself.

The file change for our *Merchants* page itself is ok, and they still do support XMR as of today, I checked.

Their [Facebook page info](https://www.facebook.com/www.bitcoinvn.io/about_profile_transparency) confirms what somebody commented already earlier here: They exist for quite a while already, almost 10 years.

They have quite favorable [reviews on Trustpilot](https://www.trustpilot.com/review/bitcoinvn.io?utm_medium=trustbox&utm_source=MicroReviewCount).

The comments in the Reddit thread mentioned above where mostly positive, including [this comment](https://old.reddit.com/r/Monero/comments/16jl506/monero_is_on_the_rise_in_vn/k0tw0fg/) from a Monero Core Team member.

I failed to find any serious problems in the past by googling them.

Right now I don't see any reason to deny them a listing. I would say let's finally merge this.

**Pull request merged**
