### PR TITLE
added link to go (golang) libraries and utilities

### PR DESCRIPTION
**Pull request by parasew**

### CODE REVIEW

**Comment by mattcode55** [comment]
Maybe it would be better to link to specific libraries instead of this index?

**Comment by parasew** [comment]
@mattcode55 yes, you are right. i originally wanted to link to the index as there are a few implementations out there. i changed it now to the most recent lib.

**Comment by parasew** [comment]
can we merge this?

**Comment by mattcode55** [comment]
Everything gets merged in a big batch whenever fp has time. Just wait :)

**Pull request merged**
