### PR TITLE
Add Cypher Stack to Sponsors page

### PR DESCRIPTION
**Pull request by rehrar**
Added Cypher Stack to sponsors page given donated work

### CODE REVIEW

**Comment by nahuhh** [comment]
title change
`sponsorships: add Cypher Stack`

**Comment by nahuhh** [comment]
You should be able to remove to strings from everything except for english
(see monero-site matrix chat)

**Comment by plowsof** [comment]
@binaryFate usually signs off on any sponsor page adjustments but this addition is widely known so not a requirement / just a nice to have for procedure otherwise ACK

**Review by plowsof — APPROVED** [review]

**Review by nahuhh — APPROVED** [review]
> Cypher Stack sponsors devops personnel to work on and maintain Monero infrastructure.

ACK

**Comment by HardenedSteel** [comment]
If Cypher Stack sponsors the project then why CCS was needed?

**Comment by nahuhh** [comment]
Diego's ccs != cypherstacks

cypherstack runs backend infra, like the matrix server

Diego's ccs is unrelated

**Review by HardenedSteel — APPROVED** [review]

**Pull request merged**
