### PR TITLE
Dev guides: add csharp-monero to 'libraries and helpers'

### LINKED ISSUE #1375: Add csharp-monero-rpc-client to 'Library and Helpers'
We are adding it to the Monero Ecosystem project: https://github.com/monero-ecosystem/meta/issues/72#issuecomment-744149987

https://github.com/Agorist-Action/csharp-monero-rpc-client (soon Agorist-Action will be replaced by monero-ecosystem)

### PR DESCRIPTION
**Pull request by erciccione**
Closes #1375

### CODE REVIEW

**Comment by Agorist-Action** [comment]
Are we waiting on someone here? If so, who? It's been a week, let's give them a poke?

**Comment by Agorist-Action** [comment]
Can we please change
```
<li><a href="https://github.com/monero-ecosystem/csharp-monero-rpc-client">csharp-monero-rpc-client</a> - {% t developer-guides.csharp-monero %}</li>
```
to
```
<li><a href="https://github.com/monero-ecosystem/csharp-monero-rpc-client">csharp-monero-rpc-client (Monero Ecosystem)</a> - {% t developer-guides.csharp-monero %}</li>
```
?

**Comment by erciccione** [comment]
> Are we waiting on someone here? If so, who? It's been a week, let's give them a poke?

We need somebody else reviewing this PR. I sometimes poke people on #monero-website but cannot really do more than that.

> Can we please change

Good point. Changed.

**Comment by rehrar** [comment]
Reviewed

**Pull request merged**
