### PR TITLE
hangouts: update matrix links

### PR DESCRIPTION
**Pull request by plowsof**
MRL has a monero.social room

### CODE REVIEW

**Review by erciccione — APPROVED** [review]
Note that the change of address is only necessary for `monero-site:haveno.network`, since that server is now offline and the address is unreachable. For this we can either use `matrix.org`, which is the original server or `monero.social`. it doesn't make any practical difference.

The address of the research lab is working. It was registered on matrix.org, but we can use monero.social.

It doesn't make any practical difference (as long as both servers stay online), but since we are changing it i would use the same server address for both rooms. We cannot use `monero-site` on the matrix server, so maybe better use monero.social, so we can use `monero-site:monero.social`

**Comment by plowsof** [comment]
agreed, much better to to be on monero.social. and to avoid -site / -website confusion

**Review by erciccione — APPROVED** [review]

**Review by hinto-janai — APPROVED** [review]

**Comment by nahuhh** [comment]
There was a suggestion to remove -hardware.
Would that be within the scope of this PR, or should a separate pr's be opened for removals and / or additions?

**Review by nahuhh — APPROVED** [review]

**Comment by plowsof** [comment]
if removing the hardware channel is decided, there is a loop in the hangouts html. which first gets all the hangouts: from en_yml
https://github.com/monero-project/monero-site/blob/c3c21f92cc62c7cdba5133cc8854e64a4c97a4bc/_i18n/en.yml#L117
and then from that list ^ it finds the links from the edited file in this PR.  deleting it from en,yml would work, but leave trash in this file so both end up being edited, i assume a separate PR that would use this one as the first commit would be better

**Pull request merged**
