### PR TITLE
Moneropedia localization

### PR DESCRIPTION
**Pull request by el00ruobuob**
We have long waited for this, so i've decided it was about time to do it.
Moneropedia, localized, finaly
This solves #700

I have briefly test it on english and polish.
I had to update a lot of polish file to make it work correctly.

It's basically working by defining a moneropedia collection per language, and require the use of a tag on every page for the ruby script to know which language it is. This tag is self-removed by the ruby script.

Also, each moneropedia entry in _i18n folder **must** have a part of the front matter (the one handled by the script) but it is interprated as md code, not as front matter. So the script has to remove it.
Please check that it does not add glitches elsewhere.

The _i18n front matter of localized files should include the english terms, so any new entry in moneropedia is working de-facto when untranslated.

We also have to document everything in the readme. I could do it later this week-end, or next week.

And of course, enjoy!

Up to the team to work @erciccione!

### CODE REVIEW

**Comment by el00ruobuob** [comment]
ping @rehrar for your clever thoughts

**Comment by el00ruobuob** [comment]
@luigi1111, could you merge #741 so that i could update this one accordingly? I would like to write the readme on top of it, and add the versionning snippet to the moneropedia entries, as there is alreay some differences between Polish and English in a bunch of articles? (Polish has been fully translated base on the template directory which had not been updated while the main /ressources/moneropedia/ was).

**Comment by el00ruobuob** [comment]
I jut made a small improvement to Ruby script to default to English moneropedia (in case an entry will be forgotten in moneropedia localized folder)

**Comment by el00ruobuob** [comment]
I have further tested today, moving to a lot of page, and i don't see any problem yet.
I'm still interested in feedbacks from @erciccione & @rehrar about it (Yes rehrar i do know you don't *understand* Ruby, i just want to discuss about the other changes and your general thoughts about them), and i look forward to make it match #741 so it could be fully integrated and the Readme could be updated without requiring a conflict-solving step.

**Comment by el00ruobuob** [comment]
I just change the code a bit to avoid reading the ./config.yml
Instead i use the `@config["languages"]` from the function, where the `@config` is available.
More elegant, less subject to build errors.

**Comment by el00ruobuob** [comment]
Great !

**Comment by erciccione** [comment]
Thank you :)

**Comment by erciccione** [comment]
@el00ruobuob please squash :)

**Comment by el00ruobuob** [comment]
Damned, i forgot to merge this last commit. Sorry @erciccione

**Comment by el00ruobuob** [comment]
Ok, now all links on Conti page (italian account) are working perfectly.
But i notice a lot of link issues in polish. Mostly terms that are not fully listed on entries i believe. I'll have to go through each polish page, compare it to english to get the destination entry, and update its terms.

**Comment by el00ruobuob** [comment]
I'm still correcting the polish at the moment. Lots of terms are missing, or unnecessary (perhaps due to the divergence between the template moneropedia directory and effective moneropedia back in time)

**Comment by el00ruobuob** [comment]
All polish-missing terms are corrected. But a full review of polish translation against the original English version might be needed. I have stored a diff from the update of English version with the latest data which may help @zofiazinha to focus on the files that needs attention.

**Comment by el00ruobuob** [comment]
Damned, there is a collision between terms.
`<thing>` and `<thing>-<specific>`.
I did revert the word-boundary regex to match english `<thing>-based`, but now it breaks the `<thing>-<specific>` when it first match `<thing>`.
I think i have no other options than changing the regex to excluded `-based` or `-like` (after checking what is indeed used)

**Comment by el00ruobuob** [comment]
Tested : Garlic-routing now display correctly the *`<thing>-<specific>`* moneropedia entry for polish, and the *`<thing>`*`-based` for english. Nailed-it!

**Comment by el00ruobuob** [comment]
Rebased

**Comment by el00ruobuob** [comment]
I just updated the Readme.
I think i will not add the versioning stuff here, because it's not supposed to evolve after all. Once an entry has been written and review, there is a few chances it might been updated later.
What do you think @rehrar @erciccione?

I could just share the diff there was between /resources/moneropedia and /_i18n/en/resources/moneropedia with @zofiazinha [here](https://github.com/monero-project/monero-site/files/2228400/0001-Changes-from-real-moneropedia.patch.txt) for him to have a pass on the updates.

**Comment by el00ruobuob** [comment]
Did you find the time to read the README update @erciccione ?
Are we good to go?

**Comment by el00ruobuob** [comment]
ping @rehrar & @luigi1111 
If none has more comment to make, may this be merge anytime soon?

**Comment by luigi1111** [comment]
@el00ruobuob maybe after rebase. :)

**Comment by el00ruobuob** [comment]
i'm on it, please hold on

**Comment by el00ruobuob** [comment]
rebased @luigi1111

**Pull request merged**
