### PR TITLE
Crypto_profi patch - add walletmonero

### PR DESCRIPTION
**Pull request by crypto-profi**
Add walletmonero.com to the list of light wallets.

### CODE REVIEW

**Comment by erciccione** [comment]
I couldn't find any announcement of this wallet neither on /r/Monero or irc chat logs. Can somebody verify the legitimacy of this service?

Pinging the Monero Security Response Team: @fluffypony @luigi1111 @moneromooo-monero @anonimal

**Comment by mattcode55** [comment]
@erciccione It seems like the user controls their private key (like MyMonero) which is good, but the way that it appeared out of nowhere with [Changelly](https://www.reddit.com/r/Monero/wiki/avoid#wiki_exchanges) integration is quite suspect.

**Comment by QuickBASIC** [comment]
Yeah no. Even if this wallet was totally legit, if anything it should probably be listed from the merchants page to begin with. Not on the main downloads page.

This PR is adding this wallet under the heading that has this text (emphasis mine):
> The following are mobile or light wallets **that are deemed safe by trusted members of the community.** If there is a wallet that is not on here, you can request the community check it out. Go to our Hangouts page to see where we are.

It appears he posted it on his Twitter [[Link]](https://twitter.com/CryptoProfi/status/922959935880728576) the other day. 

It's possible this is just a misunderstanding, but his GitHub was opened 2017-10-20 and he didn't post announcements or information in any of our communities, which to me is somewhat suspect. 

There's no way we should merge this.

**Comment by serhack** [comment]
Hello,

I prefer the "Merchant page" instead of Downloads page. I can tell you: I have some doubs about privacy and security. The backend seems OpenMonero.
At the moment, I can't trust this service.

**Comment by SamsungGalaxyPlayer** [comment]
Playing devil's advocate, MyMonero is on the downloads page. I don't mean to suggest that WalletMonero is secure or insecure (I have not evaluated this service), but if it is considered similarly secure to MyMonero, then MyMonero should not get special treatment.

**Comment by QuickBASIC** [comment]
@SamsungGalaxyPlayer 

I disagree. MyMonero has been used and vetted by the community for several years. While it's possible we could list other 3rd party wallets in the downloads page in the future, this wallet is brand new and appeared out of nowhere and has not been tested by the community nor have the developers made any announcements on our Reddit or discussed anything in IRC.

This PR is adding this wallet under the heading that has this text (emphasis mine):
> The following are mobile or light wallets **that are deemed safe by trusted members of the community.** If there is a wallet that is not on here, you can request the community check it out. Go to our Hangouts page to see where we are.

This is the standard the community had set for being listed on this page and it had not been met.

**Pull request closed without merging**
