### PR TITLE
user-guides: fix toc for verification guide

### PR DESCRIPTION
**Pull request by selsta**
Before
Before screenshot
After
After screenshot

Fix by @plowsof

### CODE REVIEW

**Review by erciccione — COMMENTED** [review]
Have you checked that this doesn't break other existing H3 header? (haven't checked myself yet)

**Comment by selsta** [comment]
I did not.

**Comment by plowsof** [comment]
Good point, i think a custom id tag for this specific fix would be ideal, i will have a look and offer the suggestion

**Comment by plowsof** [comment]
Here's styling for those specific id's (who decided on double dashes/singledashes ^^)
```
h3#--install-gnupg, 
h3#--verify--import-signing-key, 
h3#--download--verify-hash-file, 
h3#--download--verify-binary {
	margin-top: 0rem;
}
```

**Review by erciccione — COMMENTED** [review]
This fix could be ok but it's not optimal. IMO would be better to change the structure of the Toc entirely (currently it's non-standard). What about changing the Toc of the file (`resources/user-guides/verification-allos-advanced.html`) to:

```
1. [Install GnuPG](#installing-gnupg)

2. [Verify & Import Signing Key](#verify-and-import-signing-key)

3. [Download & Verify Hash File](#download-and-verify-hash-file)

4. [Download & Verify Binary](#download-and-verify-binary)

```

**Comment by selsta** [comment]
@erciccione do I have to update every single file in `_i18n/*/resources/user-guides/verification-allos-advanced.md` and also these .po files?

**Comment by erciccione** [comment]
> @erciccione do I have to update every single file in _i18n/*/resources/user-guides/verification-allos-advanced.md and also these .po files?

No, only the english file (`_i18n/en/resources/user-guides/verification-allos-advanced.md`). The po4a script will do the rest (I will run it on all user guides later on)

**Review by erciccione — APPROVED** [review]

**Pull request merged**
