### PR TITLE
Guides updated with GUI

### PR DESCRIPTION
**Pull request by el00ruobuob**
This is the second part to solves #729.
It contains the three guides updated to GUI as asked by @SamsungGalaxyPlayer
- View Only
- Restore from keyx
- Prove payment
It also contain the non-requested one, but as needed as restore from keys:
- Restore account

All screenshots are localized. However, i cannot update Polski translation by myself, so i added the new parts in english, and put back the \{\% include untranslated.html \%\} flag.
@erciccione & @zofiazinha, up to you to handle this.

I still have to check the build of the website with this PR and will soon update with my test results (as it became usual now).

### CODE REVIEW

**Comment by el00ruobuob** [comment]
Tested ok on the following platforms:

  | Edge | IE 11 | Chrome | Firefox | Opera | Vivaldi
-- | -- | -- | -- | -- | -- | --
Windows 7 | - | OK | OK | OK | OK | OK
Windows 10 | OK | OK | OK | OK | OK | OK
Ubuntu 18.04 | - | - | OK | OK | OK | OK
CentOS 7 | - | - | - | OK | OK | OK

**Comment by el00ruobuob** [comment]
ping reviewers @mattcode55 @MaxXor

**Comment by el00ruobuob** [comment]
I'll have to update the price payment screenshot according to your comment in #735.

**Comment by el00ruobuob** [comment]
@zofiazinha GUI is translated to polish (i have updated all the screenshot accordingly), but don't worry i can copy and paste the buttons from the GUI translation file itself.

However, how would you translate:
*Prove payments* & *Check payments*?

**Comment by el00ruobuob** [comment]
I believe i'm done.
Everything is up to date, even the Polish translation.

@luigi1111 do you want this squashed?

**Comment by zofiazinha** [comment]
@el00ruobuob oh, sorry, I didn't find this info. Thanks anyway!

There is one thing I'd correct in your Edit3:
Wybierz Przywróć portfel z kluczy, nazwij swój portfel i wybierz jego lokalizację i **uzupełnij pola** Adres konta (publiczny), Klucz tylko do odczytu (prywatny) & Klucz do wydawania (prywatny).

Apart from that, you are ready to translate into Polish ;)

**Comment by el00ruobuob** [comment]
Thanks @zofiazinha ! I'm clearly not able to translate anything in polish, just to copy and paste pieces of sentences based on your previous work.

**Comment by el00ruobuob** [comment]
Squashed. Ready to merge.

**Comment by el00ruobuob** [comment]
@luigi1111 boy anymore. I have to clean the template directory.

**Comment by el00ruobuob** [comment]
@luigi1111 rebased it is.

**Comment by el00ruobuob** [comment]
ping @rehrar & @luigi1111 Could we merge this?

**Pull request merged**
