### PR TITLE
add deprecation warning to the guide pages

### PR DESCRIPTION
**Pull request by HardenedSteel**

### CODE REVIEW

**Comment by plowsof** [comment]
deprecated

**Comment by plowsof** [comment]
LGTM -docs have not began migrating relevant moneropedias but it's all in progress.

**Review by plowsof — APPROVED** [review]

**Review by nahuhh — APPROVED** [review]
LGTM

echoing plowsof: we have some work todo for user guides, but it's coming along. 

The RPC docs on dev guides are fully migrated and can have their links changed to point to
docs.getmonero.org/rpc-library/monerod-rpc
and 
docs.getmonero.org/rpc-library/wallet-rpc

**Comment by plowsof** [comment]
adapted / resolved in #2388

**Pull request closed without merging**
