### PR TITLE
[WIP] German Localization

### PR DESCRIPTION
**Pull request by shilch**
This is still WIP.  
However, we did open a PR to find other native German speakers here.  
Please comment if you want to help.

### CODE REVIEW

**Comment by MaxXor** [comment]
Ehm, we're not only translating the strings but each page is also duplicated with all formatting? Isn't that a huge additional maintenance effort?

**Comment by rehrar** [comment]
Yes, yes it is. I originally tried to do simply a ton of strings, but things broke as some languages are more verbose than others. Sadly, in order for this to be achievable on an aesthetic level, it has to be done this way. 

Any other person is welcome to try to make the "strings" method work.

**Comment by rehrar** [comment]
To clarify further, I will be going through each language as it is merged and tweaking any HTML that needs to be tweaked to get it working, per language. No, it won't be fun.

**Comment by leonklingele** [comment]
@shilch in case this is still wip, I can help you out in about 3 weeks.

**Comment by shilch** [comment]
@leonklingele Great!
You can find my mail address if you navigate to `https://api.github.com/users/shilch/events/public` and search for the string `"668e81aedd3a4ef42d90d86fa95cce0e544afe70"`. (I do not want a search engine or bot see this address)

**Comment by erciccione** [comment]
Hey @shilch can you rebase this and remove the `[WIP]`?  so we can merge it, you can open another PR when you have new commits

**Comment by rehrar** [comment]
@shilch can we get a rebase on this? :)

**Comment by shilch** [comment]
Oh, haven't had much time to translate. Will have more time in one to two weeks. Do you really think that this is ready to merge? The translation is incomplete...

**Comment by erciccione** [comment]
Checked this localization and it's not ready to be merged as i thought. I would consider it ready at least when all the main pages are translated (`what is monero?`, `using`, `accepting`, `contributing`),

**Comment by erciccione** [comment]
Hey folks! Still working on this?

**Comment by erciccione** [comment]
pinging @shilch @krtschmr @leonklingele

**Comment by krtschmr** [comment]
ya, lets do more!

**Comment by leonklingele** [comment]
This PR should first be rebased, cleaned up, and merged. I will then work on translating some part of the outstanding texts (e.g. Moneropedia).

**Comment by shilch** [comment]
Uh, sorry. I will rebase it now.

**Comment by shilch** [comment]
@krtschmr and @leonklingele You should be able to push commits now.

**Comment by rehrar** [comment]
Sorry can this be rebased one more time (and then get a review on it for it to be merged)? :P 

Unfortunately, the way that the site is set up is that if one language is merged, any pending brand new languages need a rebase so it can only ever go one at a time. The nice thing is, this is a one time thing, so once German is merged it should be independent of the others.

French was just merged. Let's get a review of approval of the commits so far after the rebase and we can see about seeing this live!!

**Comment by shilch** [comment]
Okay, did a rebase. I noticed that someone did translate "Polski" to "Polish" all the time. Did fix this.

**Comment by luigi1111** [comment]
@shilch you actually did a merge update, which we generally discourage. @erciccione can help if needed, I think.

**Comment by shilch** [comment]
@luigi1111 I am a git noob :P
Will work on some more translations later the day

**Comment by erciccione** [comment]
hey @shilch come chat on #monero-translations or ping me on reddit, we can work on this together :)

**Comment by shilch** [comment]
@erciccione Thanks for your offer! I will contact you once most parts are translated and theirfore ready  to be merged.

**Comment by erciccione** [comment]
Hey @shilch what's the status of this PR at the moment?

**Comment by shilch** [comment]
Hey, quite busy right now and involved in some other projects. I have some uncommited translations that I will push later the week. Sadly I haven't heard anything from the other two translators.

Am 6. Mai 2018 17:09:25 MESZ schrieb erciccione <notifications@github.com>:
>Hey @shilch what's the status of this PR at the moment?
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/monero-project/monero-site/pull/594#issuecomment-386886238

-- 
Diese Nachricht wurde von meinem Android-Gerät mit K-9 Mail gesendet.

**Comment by erciccione** [comment]
maybe @rafficer or @Flenst can give you a hand with this

**Comment by shilch** [comment]
@Rafficer Nice! Almost everything except the `_i18n/de/resources folder` (which probably is the most work) is translated. This folder includes `developer-guides`, `moneropedia` and `user-guides`.
I will give you write permissions to the fork. With every commit we should only translate one file at a time to avoid conflicts.

**Comment by Rafficer** [comment]
@shilch Thank you, I will do some this weekend :)

**Comment by el00ruobuob** [comment]
Guys, if you're starting user-guides,be carrefull of the pending updates from #734 & #736.
If you really want to start the guides covered in those, you could take the new templates from those as based version für Deutsch (only, do not replace the old template in your directory to avoid conflicts), get in touch with @erciccione or me if you need help with the process, bitte.
Of course, i could provide the bunch of Deutsch screenshot if you want after (or before) your translation.

**Comment by erciccione** [comment]
@shilch @krtschmr  Status of this PR?

**Comment by Kesselkind** [comment]
So do you guys Need help? What is the status?
Nativ german Speaker here

**Comment by erciccione** [comment]
@Kesselkind @rodolfo912 This PR has clearly been abandoned, i suggest to start a new one using this as a base. You will need to clone @shilch 's repository. Let me know if you need help to do that :)

**Comment by rodolfo912** [comment]
@erciccione I will do this once I have some spare time (and no one else will have done it by then).

**Pull request closed without merging**
