### PR TITLE
remove moneroaddress.org from tools page

### LINKED ISSUE #2037: moneroaddress.org link broken under tools section
Suggest remove the link for moneroaddress.org under "address generator" section under resources > tools.

### PR DESCRIPTION
**Pull request by HardenedSteel**
closes #2037

### CODE REVIEW

**Comment by plowsof** [comment]
Do we know who was behind moneroaddress.org? its officially discontinued? (thankfully llcoins is fine)

**Review by plowsof — APPROVED** [review]

**Review by selsta — APPROVED** [review]
- Unclear who the new owner is
- These extremely outdated MyMonero photos are suspicious as they are often used by phishing sites

**Review by serhack — APPROVED** [review]

**Review by erciccione — APPROVED** [review]

**Comment by HardenedSteel** [comment]
Still there's no reason to keep it because the site doesn't have any function that we can count as tool.

**Comment by selsta** [comment]
@HardenedSteel can you undo the merge commit?

**Review by selsta — APPROVED** [review]

**Pull request merged**
