### PR TITLE
Remove LocalMonero from list of merchants

### PR DESCRIPTION
**Pull request by cottnn**
LocalMonero will close on November 7th, 2024: https://localmonero.co/blog/announcements/winding-down

### CODE REVIEW

**Comment by plowsof** [comment]
Thank you. we should only remove the translation from the en.yml file. the others dont need to be modified

**Comment by nahuhh** [comment]
Should likely go into next deploy

new ads = immediately
new accts = immediately
new trades = may 14

the rest is time for disputes, and withdrawing funds

**Comment by plowsof** [comment]
We should.consider leaving it up and displaying the above timeline for 6 months with the deletion coming after as this may help someone

**Review by HardenedSteel — APPROVED** [review]

**Comment by nahuhh** [comment]
Are the removed tl strings a problem?

@plowsof

**Comment by plowsof** [comment]
when deleting keys like this, we should _only_ make the change in the english file. weblate then deletes the unused keys (note master branch and subsequent "please squash" request so i can just resubmit this PR if its approved)

**Comment by plowsof** [comment]
replacing with #2321 which adds @HardenedSteels correct deletion method + removes localmoneros block explorer from tools.

**Pull request closed without merging**
