### PR TITLE
Fix links and names in user-guide post

### PR DESCRIPTION
**Pull request by nappex**
Some of links in user-guide post https://www.getmonero.org/resources/user-guides/verification-allos-advanced.html were invalid and doesn't work correctly.

Then I changed also the name of link because the number name which is nowhere in article is confusing for readers in my opinion...

### CODE REVIEW

**Review by erciccione — CHANGES_REQUESTED** [review]
Please only edit the english file

**Review by erciccione — CHANGES_REQUESTED** [review]
Please squash your commits into only 1, then we'll be ready to merge this

**Comment by nappex** [comment]
Done. May I ask you why you want to fix only english version?

**Review by erciccione — APPROVED** [review]
@nappex translations are dealt with by a script.

**Pull request merged**
