### PR TITLE
RTL support for Arabic language

### PR DESCRIPTION
**Pull request by Daniel-Leedan**
#1043

### CODE REVIEW

**Comment by Daniel-Leedan** [comment]
@erciccione This is my first github contribution, thanks for the feedback.

As a Hebrew speaker I am a little sensitive about RTL styles, sorry about that :)

Anyway, I got you. What do you think about much smaller changes like that:

```css
.nav-items {
    direction: rtl;
}

.white-nav .nav-item .dropdown-content {
	direction: rtl;
	text-align: right;
}

.site-wrap {
    text-align: right;
}

h2#main-h2 {
    text-align: right;
}

.using h2 {
    text-align: right;
}

.footer-wrapper {
	direction: rtl;
}
```

Further to your feedback, the changes are much simpler and easier to maintain. 24 lines of code.

**Comment by erciccione** [comment]
> This is my first github contribution

Welcome! If you are interested in following the development of the website, consider joining the `#monero-site` room on Freenode, matrix or mattermost

> What do you think about that?

That looks very good :)

**Comment by erciccione** [comment]
Now it's ok. We can PR improvements later on if we want to.

I guess you are using git locally on your computer. Can you squash your commits into 1? Let me know if you need help.

**Comment by Daniel-Leedan** [comment]
Github desktop, I didn't found any Instructions about commits squash via the desktop version.

I tried some YouTube guides but i found myself removing the repository... I got lost.

What should i do next?

**Comment by erciccione** [comment]
I don't know how github desktop works, but don't worry shouldn't be a problem. @luigi1111 should be able to squash when merging (i tested it, no conflicts)

**Comment by Daniel-Leedan** [comment]
Great! Let me know if there's anything else I can do.

**Pull request merged**
