### PR TITLE
Update emission and inflations YoY % changes in "This Year in Monero - 2022" blog post

### PR DESCRIPTION
**Pull request by sethforprivacy**

### CODE REVIEW

**Review by plowsof — COMMENTED** [review]
Does the network upgrade file contain updates? or its unrelated?

before:
before_sethpr
after:
after_sethpr

Looks perfect, no issues

**Comment by sethforprivacy** [comment]
No, the initial commit was just an accidental carryover from my old branch but has no changes. I will squash before merging once approved.

**Comment by sethforprivacy** [comment]
Cleaned up those changes, they actually would have created a duplicate blog post. Will squash before merge to cleanup commit history.

**Review by plowsof — APPROVED** [review]

**Comment by sethforprivacy** [comment]
Rebased/squashed.

**Review by erciccione — APPROVED** [review]

**Pull request merged**
