### PR TITLE
contributing: add view key + primary address

### LINKED ISSUE #2071: Display viewkeys of the general fund / ccs
User selenze asks ' the ccs keys may need to be displayed somewhere along with the gf and to include their view keys. ' 

```
ccs
43H2k6iDgyfNo4HzgQKF8ABALWGpRz9Ez6uexXLGFyuC32SevoaGUiKWbebSkqy5EzdkviwJ4NQwDHkxVxHceUtLBzBjoTV
645936bdbb2e13830f587351b73b226c7c107ff94e5db0e0dd19c661cd657b0a
```
General fund info found in this blog post:
https://www.getmonero.org/2021/06/24/general-fund-2020-2021-report.html

Is there an easy place to display this somewhere on site? or should it be on the ccs front end (not here)

### PR DESCRIPTION
**Pull request by HardenedSteel**
closes #2071

### CODE REVIEW

**Review by plowsof — APPROVED** [review]

**Comment by plowsof** [comment]
LGTM just need several approvals as we're editing the donation address here. perhaps people have an opinion on how to display the keys.

**Comment by plowsof** [comment]
you made a great point about people seeing "primary address" and donating to that instead, which is _fine_ but may confuse people with a view only wallet. 

Hiding them behind 1 summary that has the text "> View-only wallet" could be better

**Comment by nahuhh** [comment]
> Hiding them behind 1 summary that has the text "> View-only wallet" could be better 

Seconded

**Review by nahuhh — APPROVED** [review]
LGTM

**Review by plowsof — APPROVED** [review]

**Review by selsta — APPROVED** [review]

**Pull request merged**
