### PR TITLE
Translation from English to spanish faq.md 1040 w

### PR DESCRIPTION
**Pull request by ackseriam**
This is my second contribution. I hope you like it 1260011

### CODE REVIEW

**Comment by erciccione** [comment]
Thanks! could you squash the first two commits please?

**Comment by ackseriam** [comment]
Honestly, I had not done this. Can you help me? @erciccione

**Comment by erciccione** [comment]
Hey @ackseriam . sure i can, i think the easier way here is to add me as a collaborator to your repo, so i can squash those commits for you and push the changes

**Comment by erciccione** [comment]
@ackseriam just saw your messages on `#monero-translations` but i was offline. We can meet a day and go through this together

**Comment by ackseriam** [comment]
@erciccione ready, you are a collaborator in my repo. :)

**Comment by erciccione** [comment]
@ackseriam i see you have two commits about `downloads.md` but i thought this PR was just about `faq.md`. Why are they here? is #607 correct and ready or these commits are needed?

**Comment by ackseriam** [comment]
Sorry, it was a confusion. They are two different files. With two different changes. again apologize for so much inconviente.

**Comment by erciccione** [comment]
Don't worry, git's workflow can be very confusing. So, can i remove the two commits about `downloads.md` and leave only the one about `faq.md`?

**Comment by ackseriam** [comment]
Yes, not problem ;)

**Comment by ackseriam** [comment]
I will continue contributing @erciccione  . If you allow me. I hope to learn from my mistakes haha.  I just want you that send me a guide on how to solve the problem for future contributions. Please :)

**Comment by erciccione** [comment]
You don't need anybody to allow you, Monero is an open project, anybody is welcome to contribute:) I'm looking forward to your future works, i suggest you to take a look to git's workflow. Some useful links:

+ [GitHub's guide](https://help.github.com/categories/collaborating-with-issues-and-pull-requests/)
+ [Interactive guide on git branching](https://learngitbranching.js.org/)
+ [How to rebase a pull request](https://github.com/edx/edx-platform/wiki/How-to-Rebase-a-Pull-Request)
+ [Collaborative GitHub workflow](http://www.eqqon.com/index.php/Collaborative_Github_Workflow)

I will be happy to help you with git/github next time. just contact me on `#monero-translations` :) or on reddit (/u/ErCiccione)

**Pull request merged**
