### PR TITLE
Torrent file and magnet link for blockchain bootstrap and GUI/CLI releases on the downloads page

### PR DESCRIPTION
**Pull request by sunday-afternoon**
#508

How the change looks on the website:

torrent monero screenshot

### CODE REVIEW

**Comment by mattcode55** [comment]
Maybe we could have a torrent containing all of the GUI/CLI downloads too.

**Comment by sunday-afternoon** [comment]
I'm working on that, I can only get 50kb/s down from getmonero.org. Is it being throttled? If I can get the GUI/CLI downloads I could make it.

**Comment by mattcode55** [comment]
I noticed that the downloads from getmonero.org are very slow too. [Luckily you can grab the binaries from the GitHub release page](https://github.com/monero-project/monero/releases), although apparently not the 64-bit Windows build of 0.11.1.0.

**Comment by SamsungGalaxyPlayer** [comment]
How often is the bootstrap updated? If it's updated frequently, then it's unlikely there will be an advantage of using a torrent.

**Comment by MaxXor** [comment]
We could just link to the binaries on github to reduce the load on getmonero.org website. I noticed the slow downloads as well.

**Comment by sunday-afternoon** [comment]
CLI/GUI torrents added. 

All GUI releases from github are in one torrent and all the CLI releases from github (plus the windows64 release from getmonero) are in another torrent.

How the change looks on the website:

monero-screen-shot-update

**Comment by MaxXor** [comment]
What about the downloads from github as most non-techy people don't use torrents?

**Comment by sunday-afternoon** [comment]
@MaxXor There are only two separate torrents (GUI / CLI). I put multiple links on the page to try and make it clear to the user that if they wanted that version of the release via torrent they could get it by clicking the link. 

Torrents are generally for more technical users and are a more decentralized model than direct download from github or any one server.

**Comment by MaxXor** [comment]
This doesn't address the slow downloads for non-techy people. I don't agree that we get much benefit from torrents of the CLI + GUI. Usually as a techy person myself I rather download from a direct link than start my torrent client and add the torrent.

**Comment by sunday-afternoon** [comment]
This pull request really wasn't meant to address slow download speeds. Adding torrents as an alternative download method makes distribution more decentralized. I'm slightly confused why there needs to be any more benefit than that.

**Comment by luigi1111** [comment]
Someone please double check that the files are all the correct ones. I'm not sure about the bootstrap file as it won't be kept up to date as much, but that may be ok.

**Comment by sunday-afternoon** [comment]
[CLI Magnet Link:](magnet:?xt=urn:btih:cf08ca86a2d2f72631b994985639acc206d3500e&dn=monero-cli-v0.11.1.0&tr=udp%3a%2f%2ftracker.opentrackr.org%3a1337%2fannounce)

**Comment by mkell43** [comment]
A user on reddit pointed out (https://www.reddit.com/r/Monero/comments/7oznm8/help_verify_and_then_seed_monero_cligui_torrents/dsejsiv/) that we don't have, or maybe they weren't found, official hashes for the source files included in the torrents.  That said, I was able to confirm the hashes for the other files.

```bash
mkell43@monolith:~/monero-things$ diff -y monero-torrent-hashes.list monero-hashes.list 
monero-dragonflybsd-x64-v0.11.1.0.tar.bz2,30e2d50db8e1738a72d   monero-dragonflybsd-x64-v0.11.1.0.tar.bz2,30e2d50db8e1738a72d
monero-freebsd-x64-v0.11.1.0.tar.bz2,bd2090f643d212a4031edbf4   monero-freebsd-x64-v0.11.1.0.tar.bz2,bd2090f643d212a4031edbf4
monero-gui-linux-x64-v0.11.1.0.tar.bz2,e18a13f39a3b4aa87c9afd   monero-gui-linux-x64-v0.11.1.0.tar.bz2,e18a13f39a3b4aa87c9afd
monero-gui-linux-x86-v0.11.1.0.tar.bz2,5df6ebeab728a653eaf643   monero-gui-linux-x86-v0.11.1.0.tar.bz2,5df6ebeab728a653eaf643
monero-gui-mac-x64-v0.11.1.0.tar.bz2,4f63ac3e9c5f87f8d8318ff8   monero-gui-mac-x64-v0.11.1.0.tar.bz2,4f63ac3e9c5f87f8d8318ff8
monero-gui-win-x64-v0.11.1.0.zip,39d16f40fccf532b0193f33afd5a   monero-gui-win-x64-v0.11.1.0.zip,39d16f40fccf532b0193f33afd5a
monero-linux-armv7-v0.11.1.0.tar.bz2,72d48a83189e3f99e7bd3d0c   monero-linux-armv7-v0.11.1.0.tar.bz2,72d48a83189e3f99e7bd3d0c
monero-linux-armv8-v0.11.1.0.tar.bz2,f1f0850e37eb65595d8e92eb   monero-linux-armv8-v0.11.1.0.tar.bz2,f1f0850e37eb65595d8e92eb
monero-linux-x64-v0.11.1.0.tar.bz2,6581506f8a030d8d50b38744ba   monero-linux-x64-v0.11.1.0.tar.bz2,6581506f8a030d8d50b38744ba
monero-linux-x86-v0.11.1.0.tar.bz2,ef212bda6b9a30af2a3e7e94cb   monero-linux-x86-v0.11.1.0.tar.bz2,ef212bda6b9a30af2a3e7e94cb
monero-mac-x64-v0.11.1.0.tar.bz2,75b12623760574688572adfb1050   monero-mac-x64-v0.11.1.0.tar.bz2,75b12623760574688572adfb1050
monero-win-x64-v0.11.1.0.zip,81f80876b5ce95b4c94b858bd4b57d2a   monero-win-x64-v0.11.1.0.zip,81f80876b5ce95b4c94b858bd4b57d2a
monero-win-x86-v0.11.1.0.zip,d1c1c2e75211143f935c2e06cf09892e   monero-win-x86-v0.11.1.0.zip,d1c1c2e75211143f935c2e06cf09892e
```

**Comment by erciccione** [comment]
I'm checking hashes and source files. Results:
(checked if the resulting hash correspond to the hash listed on https://getmonero.org/downloads )

**CLI**
- [x] monero-linux-x64-v0.11.1.0.tar.bz2
- [x] monero-linux-armv8-v0.11.1.0.tar.bz2
- [x] monero-dragonflybsd-x64-v0.11.1.0.tar.bz2
- [x] monero-linux-armv7-v0.11.1.0.tar.bz2
- [x] monero-linux-x86-v0.11.1.0.tar.bz2
- [x] monero-mac-x64-v0.11.1.0.tar.bz2
- [x] monero-win-x86-v0.11.1.0.zip
- [ ] monero-0.11.1.0.tar.gz (source code)
- [ ] monero-0.11.1.0.zip (source code)

both source files (tar.gz and zip) differ from the code in [releases](https://github.com/monero-project/monero/releases/tag/v0.11.1.0) in two different files:    
`src/wallet/api/wallet.cpp`
```
+    // in case new wallet, this will force fast-refresh (pulling hashes instead of blocks)
+    // If daemon isn't synced a calculated block height will be used instead
+    if (isNewWallet() && daemonSynced()) {
+        LOG_PRINT_L2(__FUNCTION__ << ":New Wallet - fast refresh until " << daemonBlockChainHeight());
+        m_wallet->set_refresh_from_block_height(daemonBlockChainHeight());
+    }
+
     if (m_rebuildWalletCache)
       LOG_PRINT_L2(__FUNCTION__ << ": Rebuilding wallet cache, fast refresh until block " << m_wallet->get_refresh_from_block_height());

```
`version.cmake`

```
file(MAKE_DIRECTORY "${CMAKE_BINARY_DIR}/version")
 find_package(Git QUIET)
-if ("$Format:$" STREQUAL "")
+if ("" STREQUAL "")
   # We're in a tarball; use hard-coded variables.
   write_static_version_header("release")
 elseif (GIT_FOUND OR Git_FOUND)

```
Also, there are two versions of the source code, one in .tar.gz and the other one in .zip . Since they are they same repository, wouldn't be better to keep the .zip file only?

**GUI**
(in progress)
- [ ] monero-gui-mac-x64-v0.11.1.0.tar.bz2
- [ ] monero-gui-win-x64-v0.11.1.0.zip
- [ ] monero-gui-linux-x64-v0.11.1.0.tar.bz2
- [ ] monero-gui-0.11.1.0.tar.gz
- [ ] monero-gui-0.11.1.0.zip
- [ ] monero-gui-linux-x86-v0.11.1.0.tar.bz2

**Comment by rehrar** [comment]
@sunday-afternoon can we rebase this to see about getting it merged? :)

**Comment by sunday-afternoon** [comment]
@rehrar sure, might as well go for magnet links to the new hardfork binaries at this point?

**Pull request closed without merging**
