### PR TITLE
sponsorships: add disclaimer

### PR DESCRIPTION
**Pull request by plowsof**
more details? suggestions welcome

### CODE REVIEW

**Review by erciccione — COMMENTED** [review]
I'd use something more verbose, like

> Note: Sponsors are benefactors that made generous or recurring donations to the Monero project. Being listed on this page doesn't necessarily imply endorsement from the Getmonero team. Do your own research before trusting any service with your money.

Or we could reuse the disclaimer in the merchants page:

https://github.com/monero-project/monero-site/blob/6cd7e19300e17847b80d33091b3cb333af7a2a46/_i18n/en.yml#L148

**Comment by erciccione** [comment]
Any feedback on the first option?

> Note: Sponsors are benefactors that made generous or recurring donations to the Monero project. Being listed on this page doesn't necessarily imply endorsement from the Getmonero team. Do your own research before trusting any service with your money.

**Comment by MajesticBank** [comment]
I am more in favour of disclaimer on the merchants page, somehow sounds more explanatory and seems legally covering wider area
and maybe if (?) move it below the table

**Comment by nahuhh** [comment]
merchant page disclaimer sounds better

**Comment by plowsof** [comment]
I think a verbose text "above" the sponsors feels out of place. My guess is that many users reading this would misinterpret it as saying "you can definitely not trust any of these, that's why we have a big disclaimer", i wouldn't want my business right under that. so it should be a footer like the merchants text @erciccione linked.

**Comment by erciccione** [comment]
Reusing the disclaimer is the easier option. Would you adapt the PR @plowsof?

**Comment by plowsof** [comment]
added the disclaimer to the bottom, see how it looks https://deploy-preview-2141--barolo-time-757cf9.netlify.app/community/sponsorships/

**Review by erciccione — APPROVED** [review]

**Review by nahuhh — APPROVED** [review]

**Pull request merged**
