### PR TITLE
Add a "fork me on github ribbon"

### PR DESCRIPTION
**Pull request by ChristopherKing42**

### CODE REVIEW

**Comment by fluffypony** [comment]
Hmmmm...my concern is that the "fork me on Github" thing normally points to the main project, not the website. In lieu of this, what if we had an "Edit this page" link at the bottom of each page?

**Comment by ChristopherKing42** [comment]
Would changing the url to the main project work. (Also, I like the idea of a "Edit this page" link, especially for moneropedia. That would probably be best for another pull request though.)

**Comment by JamesCullum** [comment]
I would prefer a smaller "Edit this page" as well, the "Fork me on GitHub" looks kind of weird on a big scale website and i dont think it needs this much of a focus.

**Comment by fluffypony** [comment]
Closing in favour of "edit this page"

**Pull request closed without merging**
