### PR TITLE
add BitcartCC to tools page

### PR DESCRIPTION
**Pull request by HardenedSteel**

### CODE REVIEW

**Comment by MrNaif2018** [comment]
Hi! Is there anything needed to get this merged @erciccione?
Thanks!

**Comment by plowsof** [comment]
BitcartCC is under active development. It allows people to "Start Accepting Crypto Payments [including Monero] With 0% Fees & No Third-party" with plenty of docs and third-party plugins. the developer @MrNaif2018 has been in contact with the Monero dev community over the past several months to brainstorm ideas / ask foe support, i see no problem with listing this service on getmonero

**Review by plowsof — APPROVED** [review]

**Review by erciccione — COMMENTED** [review]
> Hi! Is there anything needed to get this merged @erciccione?

Just some more people to review it. I don't know this service and never used it, so i cannot assess if it's stable/secure enough to be actively suggested on getmonero.

**Comment by slade991** [comment]
Hello,
we use it at https://servers.guru for a while, and i can completely vouch for it. 
Great tool for merchant, and great way to help adoption.

**Review by erciccione — APPROVED** [review]

**Review by erciccione — COMMENTED** [review]
Please squash

**Review by erciccione — APPROVED** [review]

**Comment by plowsof** [comment]
monerosupplies.com is now using bitcart as a payment processor (i have no affiliation)

**Comment by MrNaif2018** [comment]
As well as many other our monero users due to ease of integration (:
In fact, for some of our merchants monero is the dominating currency (i.e. with servers.guru in server market)
I think this can be merged because many servers with bitcart already utilize monero

**Pull request merged**
