### PR TITLE
Add Coin Wallet

### PR DESCRIPTION
**Pull request by mahnunchik**
This PR adds [Coin Wallet](https://coin.space/monero-wallet/) a non-custodial multicurrency crypto wallet to the download page.

* Coin Wallet was launched in 2014
* Monero support was added [July 2021](https://github.com/CoinSpace/CoinSpace/releases/tag/v4.0.0)

Main repo is here: https://github.com/CoinSpace/CoinSpace

Client code is completely open source. Links to monero part:
* https://github.com/CoinSpace/cs-monero-wallet
* https://github.com/CoinSpace/monero-core-js
* https://github.com/CoinSpace/monerolib

Almost two year have passed since the last request to add Coin Wallet to download page: https://github.com/monero-project/monero-site/pull/1725

### CODE REVIEW

**Review by erciccione — COMMENTED** [review]
Waiting for feedback

**Comment by MajesticBank** [comment]
One questions just if wallet is fully non-custodial, how do you charge monero transfer fee like 0.5% ?

Monero | Network fee + 0.5% (min. $0.30, max. $100)

**Comment by MajesticBank** [comment]
https://imgur.com/a/qS64LbL

**Comment by mahnunchik** [comment]
@mahnunchik fee is calculated on the client side when creating a transaction https://github.com/CoinSpace/cs-monero-wallet/blob/master/index.js#L714-L715

**Comment by MajesticBank** [comment]
I suppose you are talking about Network fee ?

How about + 0.5% (min. $0.30, max. $100) ?

**Comment by MajesticBank** [comment]
Sorry after a short review, wallet send request to your backend to obtain % of fee you are charging user on top of network fee and then add additional output to the transaction with your address + fee amount ?

Got it right ?

async #loadCsFee() {
    try {
      const result = await this.#requestWeb({
        url: 'api/v3/csfee',
        params: {
          crypto: 'monero@monero',
        },
        method: 'get',
        seed: 'public',
      });
      this.#csFee = result.fee;
      this.#csMinFee = new BigNumber(result.minFee, 10);
      this.#csMaxFee = new BigNumber(result.maxFee, 10);
      this.#csSkipMinFee = result.skipMinFee || false;
      this.#csFeeAddresses = result.addresses;
      this.#csFeeOff = result.addresses.length === 0
        || result.whitelist.includes(this.#getAddress('address'));
    } catch (err) {
      console.error(err);
    }
  }

**Comment by mahnunchik** [comment]
@MajesticBank you are right

**Comment by nahuhh** [comment]
NACK

**Comment by jermanuts** [comment]
The problem with web based wallets is that they could always target you with a backdoored version of their web client as they rely on the server dynamically serving JavaScript code to the browser to handle cryptography and/or steal your seeds.

**Comment by plowsof** [comment]
NACK the dynamic/on-the-fly nature of how fees are scraped from each transaction.

**Comment by plowsof** [comment]
closing following the feedback received here

**Pull request closed without merging**
