### PR TITLE
Logs for the Kovri and Dev meetings held on 2017-03-26

### PR DESCRIPTION
**Pull request by dEBRUYNE-1**

### CODE REVIEW

**Comment by anonimal** [comment]
Thanks @dEBRUYNE-1

**Comment by jonathancross** [comment]
Ping @fluffypony - Would be great to get these onto the site ;-)

**Comment by dEBRUYNE-1** [comment]
Added "Logs for the Kovri and Dev meetings held on 2017-04-09".

**Comment by anonimal** [comment]
Thank you @dEBRUYNE-1. @fluffypony ETA?

**Comment by anonimal** [comment]
@dEBRUYNE-1 did you happen to log the April 23rd meeting too?

**Pull request merged**
