### PR TITLE
Added Monero Outreach Quickfacts to library

### PR DESCRIPTION
**Pull request by lh1008**
Hi from the [Monero Outreach Workgroup](https://github.com/monero-outreach),

We would like to add a document worked by the team and shared through the community through a [reddit post](https://www.reddit.com/r/Monero/comments/8k0rby/monero_quickfact_sheet_for_journalists_investors/). 

We have been working on several educational materials to get more Monero awareness. Our first goal was "to create a tool that can be shared with journalists and reduce the amount of inaccurate publicity." ([taiga instance 24](https://taiga.getmonero.org/project/xmrhaelan-monero-public-relations/us/24?milestone=29)), and that's where the [Quick-Facts sheet](http://www.monerooutreach.org/pubs/2018/QuickFacts/QuickFacts.pdf) was born.

The document will be updated regularly so the community can benefit from it. We are working to have the sheet in different languages. We have already translated the document into Spanish(es), so in the PR you will see two documents added to the `directory/library`(en and es) and we also updated the `*.yml` files respectively, following the [monero website instructions](https://github.com/monero-project/monero-site). Building in Jekyll is working properly. Made tests and the links are working great. Did not encounter with any bugs or trouble in the process.

If you have any questions or have any suggestions about the content, please let us know.

Thank you :)

### CODE REVIEW

**Comment by el00ruobuob** [comment]
I wonder if `magazines` is the proper category. I think we could add one. Maybe `press documentation` or something?

**Comment by lh1008** [comment]
Yes, I like the `press documentation` category. I was wondering if `magazines` was the correct category. I didn't add another category because I wasn't sure if that affected the building construction, and I was not sure what name to use.

**Comment by lh1008** [comment]
Ok, thank you. I will do the changes.

**Comment by SamsungGalaxyPlayer** [comment]
What about adding it to the `press-kit` page? https://getmonero.org/press-kit/

**Comment by el00ruobuob** [comment]
I think this was initially the goal. But @rehrar had to add a section for it in the page (which he didn't find the time to do or forget about)

**Comment by lh1008** [comment]
@SamsungGalaxyPlayer it will be a good idea to finish the section for the Press-kit section. I think quickfacts could be there. I will be adding it to the library/section by now. When the section is ready we could change it.

**Comment by lh1008** [comment]
@el00ruobuob ok, I did the file changes and added the category - Press Documentation. I was not able to come up with another name, so I left it as you suggested :). Build in jekyll and no bugs no conflicts.  

If there is anything else we have to do, please let us know.

**Comment by lh1008** [comment]
Hi @el00ruobuob 

Squashed into 1 commit.

**Comment by el00ruobuob** [comment]
Great! I cannot build test at the moment. Is it building and displaying correctly?

**Comment by lh1008** [comment]
@el00ruobuob I removed the date so we won't have any misunderstandings. Please let me know if this is ok. Updated in al the `*.yml` files and in jekyll is building properly.

**Comment by el00ruobuob** [comment]
This way is fine too, but I have a preference for a specific date of data extraction indicated. Let see what the others may think about it. @SamsungGalaxyPlayer ?

**Comment by lh1008** [comment]
@el00ruobuob I will be closing the PR and making a new PR about "Adding the Quickfacts to Press-kit section" because I missed something already spoken in the Monero Outreach community and shared through the community in [this Reddit thread](https://www.reddit.com/r/Monero/comments/8l4kzk/monero_quickfact_sheet_is_complete/):
>"xmrhaelan
This was created with the feedback of community members on IRC, Reddit, and our blossoming PR, O&E taiga project. Big thanks to everyone who contributed and offered feedback.
I intend to update this periodically to reflect changes in Monero stats and developments, so be sure to check https://getmonero.org/press-kit/ or https://taiga.getmonero.org/project/xmrhaelan-monero-public-relations/ every so often if you’re looking for an updated copy to share with folks.
It will not appear on getmonero.org until current pull request has been merged.
I hope this helps you better understand Monero or better explain it to others!"

Where @xmrhaelan  addressed to the community members that it was going to be added to the https://getmonero.org/press-kit/ section. @SamsungGalaxyPlayer also said something in a comment above:

>What about adding it to the press-kit page? https://getmonero.org/press-kit/

But he didn't add more comments about this, until I recieved feedback from @xmrhaelan today.

I'm really sorry for all the time you bothered to add the Quickfacts to the library. I will be working on a new PR for the Press-kit section. 

About:
>This way is fine too, but I have a preference for a specific date of data extraction indicated. Let see what the others may think about it. @SamsungGalaxyPlayer ?

We are trying to add the Quickfacts to the getmonero.org site in such a way that our future updates to that document won’t require a new PR. If we add a Date (YYYY-MM-DD) we will require to do PRs each time we add a new document with a new date. When you gave me your comments about adding the date, I removed the date so we wouldn't have to change the date in the future in a new PR.

**Pull request closed without merging**
